# Generated by Django 6.0.2 on 2026-02-05 11:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0019_alter_clinic_type'),
        ('gateway', '0001_create_gateway_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('namespace', models.CharField(blank=True, help_text='Azure Relay namespace (e.g., myrelay.servicebus.windows.net)', max_length=255)),
                ('hybrid_connection_name', models.CharField(blank=True, help_text='Azure Relay hybrid connection name', max_length=255)),
                ('key_name', models.CharField(blank=True, help_text='Azure Relay shared access policy name', max_length=255)),
                ('shared_access_key_variable_name', models.CharField(blank=True, help_text='Environment variable name containing the shared access key', max_length=255)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinics.provider')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
