# Generated by Django 6.0.2 on 2026-02-11 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0002_relay'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatewayaction',
            name='failed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
