# Generated by Django 6.0.3 on 2026-03-11 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0003_gatewayaction_failed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatewayaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('confirmed', 'Confirmed'), ('failed', 'Failed'), ('image_failed', 'Image Failed')], default='pending', max_length=20),
        ),
    ]
