# ruff: noqa: F403, F405
from os import environ

# Force the personas setting on, ensuring that the URL will be included in
# the URLConf
environ["PERSONAS_ENABLED"] = "1"

from .settings import *

SECRET_KEY = "testing"

STORAGES = {
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
    "dicom": {
        "BACKEND": "django.core.files.storage.InMemoryStorage",
    },
}

MIDDLEWARE.remove(
    "whitenoise.middleware.WhiteNoiseMiddleware",
)

if DEBUG:
    INSTALLED_APPS.remove("debug_toolbar")
    MIDDLEWARE.remove("debug_toolbar.middleware.DebugToolbarMiddleware")
    DEBUG_TOOLBAR = False

# CIS2 / Authlib configuration
CIS2_SERVER_METADATA_URL = (
    "http://example.com/test/oidc/.well-known/openid-configuration"
)
CIS2_CLIENT_ID = "test-client"

# Test RSA key pair - DO NOT USE IN PRODUCTION
CIS2_CLIENT_PRIVATE_KEY = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC7VJTUt9Us8cKj
MzEfYyjiWA4R4/M2bS1GB4t7NXp98C3SC6dVMvDuictGeurT8jNbvJZHtCSuYEvu
NMoSfm76oqFvAp8Gy0iz5sxjZmSnXyCdPEovGhLa0VzMaQ8s+CLOyS56YyCFGeJZ
40mboQ5UbTbOcCsXkLIuHpNSMjpPnH5Kl8Yk2XFtPYSHtVQgTQtKfX9JfsZrBRVc
aBNET8Tl4YnZ5yYEJQG2FNEJAnqDsL+auTBYMXj1vXZ8yjHSCQagndwNFJWWXaYS
LgWYJgJ1Y4bvQYgXRwWw7k9KcoBGSkxuQLEnjJQiQb3pLDdVFdD2VUWdTJKTW8fk
XRz5wMJBAgMBAAECggEADEEwgkjZfFDR84LQJ2L0/TIZGzcC2uKLTH7JHbv0+5OE
QVKOTqaLrYJFoYAK37Nb0Lh+O4V/3BGi4o60VM7kzO0xKG2zLlM9LWWHQJqHwTVY
DXuiqQFl9Gh6zdYxGV7vBLWI4AxSqKnQIfKR7CVnLwWC9o7izMeYYpO0bYwgPVo5
8+EFCg5QPJ1NpDxVaeLmCHF9gUEzAVYbFjw0wWp5+TsYHQKBgQDFJzGvQ0nv+wRj
jQ23X0AIYVm+PlBkYHZ/QpnfTqEKbTLGDMIRY9+ZmvtqmHQCxj4ZF1tKD3HfIzQz
AHDYkgANlGY5iMwMwVYG0iYGf6KRGMtHRH2QJaYpGun5m+yLgz9MO8+hCRy7WUFC
j5SQIz/rnuuS3qE4m9xLKO9rqwKBgQDyReviVUJRVHlRKMzMHGbDTHjYNgf6PvnD
SJZUaOkK1At4Vk3UPykk6DDQ1O5nUwLRUEUw6LwNP8tIiPPwWvbbIQFCRFmGRHqE
EkgRXK9+H2bnYGLSE8fuUCQdKw9MlGSE7hCiCz2ZNKbGiUGRgMwmLvEbB/8wBWGd
KqxgQCqXMwKBgEfCIrVSXvCbNR6jRWjnb6Bev0VYyG9QfvebvXJFvQXUpoLuT+0M
SjQbTbPfFGLCuC4cBYo+3QWgV2Tfi83n2D+yYdQ8p0vvDIvDYL5tHbdYlEaOzJ8J
JILxzLDGe0eIPGLcOYvQyfHEMRJAj4SAuKKVxeSKkzs3/xEYfyRHbf0RAoGBAI1z
UxR3gGXUUx+HAJtfPzj5mAYcqZhLiF9Q0QKFJQMQJxBKQWuLMtEwXagU5eTYGbYW
zIlQEo8ZXbVGp+X8qZP0ZIkiR+KbVpFYZLiXJA+DO5eDU5k/UxRtJCCpGkLJLLKz
Y2HdD5UlTRvQAJJh01DDPKIzQOlvZwKBgQCl7n8/fPd9vC0xJ8mk4iFgDHY4Mdvq
CCn2QMbCU1SxZQDPbsk0/ZYvPKcOchLITZMEMCwQjwQ7Gukx8H4rYeUQB4Qx2FjK
9FZEjlAyPHzJoK9fUfyPDbnYc0KUOIvLPEQQ8Y6BdRHG6ZJKaKIjZCZC8QJEODmj
GmwNhVP1+FNWOQ==
-----END PRIVATE KEY-----"""

# Test RSA key pair - DO NOT USE IN PRODUCTION
CIS2_CLIENT_PUBLIC_KEY = """-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAu1SU1LfVLPHCozMxH2Mo
4lgOEePzNm0tRgeLezV6ffAt0gunVTLw7onLRnrq0/IzW7yWR7QkrmBL7jTKEn5u
+qKhbwKfBstIs+bMY2Zkp18gnTxKLxoS2tFczGkPLPgizskuemMghRniWeNJm6EO
VG02znArF5CyLh6TUjI6T5x+SpfGJNlxbT2Eh7VUIE0LSn1/SX7GawUVXGgTRE/E
5eGJ2ecmBCUBthTRCQJ6g7C/mrkwWDF49b12fMox0gkGoJ3cDRSVll2mEi4FmCYC
dWOG70GIF0cFsO5PSnKARkpMbkCxJ4yUIkG96Sw3VRXQ9lVFnUySk1vH5F0c+cDC
QQIDAQAB
-----END PUBLIC KEY-----"""

# Keep basic auth off in tests by default
BASIC_AUTH_ENABLED = False
