"""
Django settings for manage_breast_screening project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import sys
from os import environ, getenv
from pathlib import Path

from dotenv import load_dotenv
from jinja2 import ChainableUndefined


def boolean_env(key, default=None):
    value = environ.get(key)
    return default if value is None else value in ("True", "true", "1")


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# loads the configs from .env in local development
load_dotenv(BASE_DIR / "config" / ".env")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = environ.get("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = boolean_env("DEBUG", default=False)

allowed_hosts = environ.get("ALLOWED_HOSTS")
ALLOWED_HOSTS = allowed_hosts.split(",") if allowed_hosts else []

allowed_hosts_except_localhost = set(ALLOWED_HOSTS) - {"localhost", "127.0.0.1"}

if allowed_hosts_except_localhost:
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True
    SECURE_SSL_REDIRECT = False

# SECURITY WARNING: don't run with PERSONAS_ENABLED turned on in production!
PERSONAS_ENABLED = boolean_env("PERSONAS_ENABLED", default=False)

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.forms",
    "qsessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "manage_breast_screening.core",
    "manage_breast_screening.auth",
    "manage_breast_screening.users",
    "manage_breast_screening.clinics",
    "manage_breast_screening.nhsuk_forms",
    "manage_breast_screening.notifications",
    "manage_breast_screening.participants",
    "manage_breast_screening.mammograms",
    "rules.apps.AutodiscoverRulesConfig",
]

if getenv("DJANGO_ENV", "production") != "production":
    INSTALLED_APPS.append("manage_breast_screening.nonprod")

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "manage_breast_screening.core.middleware.basic_auth.BasicAuthMiddleware",
    "qsessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# TODO: remove the check once we've implemented CIS2 auth. For now,
# we only apply auth protection when a viable auth method is available. This keeps our
# tests passing and prevents us forcing a sign in without a way to do so.
if PERSONAS_ENABLED:
    # Enforce auth globally only in PERSONAS_ENABLED mode
    idx = (
        MIDDLEWARE.index("django.contrib.auth.middleware.AuthenticationMiddleware") + 1
    )
    MIDDLEWARE.insert(idx, "django.contrib.auth.middleware.LoginRequiredMiddleware")

if DEBUG:
    INTERNAL_IPS = ["127.0.0.1"]

DEBUG_TOOLBAR = DEBUG
if DEBUG_TOOLBAR:
    INSTALLED_APPS.append("debug_toolbar")
    MIDDLEWARE.insert(0, "debug_toolbar.middleware.DebugToolbarMiddleware")

AUTH_USER_MODEL = "users.User"

AUTHENTICATION_BACKENDS = (
    "rules.permissions.ObjectPermissionBackend",
    "django.contrib.auth.backends.ModelBackend",
)

ROOT_URLCONF = "manage_breast_screening.core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.jinja2.Jinja2",
        "DIRS": [BASE_DIR / "jinja2"],
        "APP_DIRS": True,
        "OPTIONS": {
            "environment": "manage_breast_screening.config.jinja2_env.environment",
            "undefined": ChainableUndefined,
        },
    },
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ]
        },
    },
]

WSGI_APPLICATION = "manage_breast_screening.config.wsgi.application"
FORM_RENDERER = "django.forms.renderers.TemplatesSetting"
SESSION_ENGINE = "qsessions.backends.db"

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "manage_breast_screening.config.postgresql",
        "NAME": environ.get("DATABASE_NAME", ""),
        "USER": environ.get("DATABASE_USER", ""),
        "PASSWORD": environ.get("DATABASE_PASSWORD", ""),
        "HOST": environ.get("DATABASE_HOST", ""),
        "PORT": environ.get("DATABASE_PORT", "5432"),
        "OPTIONS": {"sslmode": environ.get("DATABASE_SSLMODE", "prefer")},
    }
}

STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"

STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_DIRS = [BASE_DIR / "static", BASE_DIR / "assets" / "compiled"]

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

LOG_QUERIES = boolean_env("LOG_QUERIES")
LOGGING = {
    "version": 1,  # the dictConfig format version
    "disable_existing_loggers": False,  # retain the default loggers
    "formatters": {
        "verbose": {
            "format": "%(asctime)s [%(process)d] [%(levelname)s] [%(module)s] %(message)s",
            "datefmt": "[%Y-%m-%d %H:%M:%S %z]",
            "class": "logging.Formatter",
        }
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
            "stream": sys.stdout,
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "DEBUG",
    },
    "loggers": {
        "django": {
            "level": "INFO",
            "handlers": ["console"],
            "propagate": False,
        },
        "django.db.backends": {
            "level": "DEBUG" if LOG_QUERIES else "INFO",
            "handlers": ["console"],
            "propagate": False,
        },
        "django.server": {
            "level": "INFO",
            "handlers": ["console"],
            "propagate": False,
        },
        "django.utils.autoreload": {
            "level": "INFO",
            "handlers": ["console"],
            "propagate": False,
        },
        "faker": {"level": "INFO"},
    },
}

AUDIT_EXCLUDED_FIELDS = ["password", "token", "created_at", "updated_at", "id"]

if PERSONAS_ENABLED:
    LOGIN_URL = "auth:persona_login"
else:
    LOGIN_URL = "auth:login"

# CIS2 / Authlib configuration
# These settings configure Authlib's Django client to use CIS2 via private_key_jwt
CIS2_SERVER_METADATA_URL = environ.get("CIS2_SERVER_METADATA_URL")
CIS2_CLIENT_ID = environ.get("CIS2_CLIENT_ID")
# Load the private key used for private_key_jwt from environment (PEM). Newlines may be provided as \n.
private_key_inline = environ.get("CIS2_CLIENT_PRIVATE_KEY")
CIS2_CLIENT_PRIVATE_KEY = (
    private_key_inline.replace("\\n", "\n") if private_key_inline else None
)
public_key_inline = environ.get("CIS2_CLIENT_PUBLIC_KEY")
CIS2_CLIENT_PUBLIC_KEY = (
    public_key_inline.replace("\\n", "\n") if public_key_inline else None
)
CIS2_SCOPES = "openid profile email nhsperson associatedorgs"
CIS2_DEBUG = boolean_env("CIS2_DEBUG", default=False)

BASE_URL = environ.get("BASE_URL")

# HTTP Basic Auth (optional; off by default)
BASIC_AUTH_ENABLED = boolean_env("BASIC_AUTH_ENABLED", default=False)
BASIC_AUTH_USERNAME = environ.get("BASIC_AUTH_USERNAME")
BASIC_AUTH_PASSWORD = environ.get("BASIC_AUTH_PASSWORD")
BASIC_AUTH_REALM = environ.get("BASIC_AUTH_REALM", "Restricted")
