name: manage_screening

services:
  app:
    env_file:
      - manage_breast_screening/config/.env
    build:
      context: .
      dockerfile: Dockerfile
    # environment:
    #   - DATABASE_HOST=db
    profiles:
      - local
    ports:
      - 127.0.0.1:8000:8000
    volumes:
      - ./manage_breast_screening:/app/manage_breast_screening

  # db:
  #   env_file:
  #     - manage_breast_screening/config/.env
  #   environment:
  #     - POSTGRES_DB=${DATABASE_NAME}
  #     - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
  #     - POSTGRES_USER=${DATABASE_USER}
  #     - SSLMODE=${DATABASE_SSLMODE}
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER}"]
  #     interval: 10s
  #     retries: 5
  #     start_period: 30s
  #     timeout: 10s
  #   image: postgres
  #   ports:
  #     - 127.0.0.1:5432:5432
  #   restart: always
  #   profiles:
  #     - local
  #   volumes:
  #     - postgres_db:/var/lib/postgresql/data

# volumes:
#   postgres_db: