# Generated by Django 6.0.1 on 2026-01-26 10:05

import django.db.models.deletion
import manage_breast_screening.dicom.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_instance_uid', models.CharField(max_length=128, unique=True)),
                ('source_message_id', models.CharField(max_length=128)),
                ('patient_id', models.CharField(blank=True, max_length=10)),
                ('date_and_time', models.DateTimeField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'indexes': [models.Index(fields=['study_instance_uid'], name='dicom_study_study_i_71786e_idx'), models.Index(fields=['patient_id'], name='dicom_study_patient_a0d130_idx'), models.Index(fields=['source_message_id'], name='dicom_study_source__7da9e7_idx')],
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_instance_uid', models.CharField(max_length=128, unique=True)),
                ('modality', models.CharField(blank=True, max_length=16)),
                ('series_number', models.IntegerField(blank=True, null=True)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='dicom.study')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sop_instance_uid', models.CharField(max_length=128, unique=True)),
                ('instance_number', models.IntegerField(blank=True, null=True)),
                ('dicom_file', models.FileField(storage=manage_breast_screening.dicom.models.dicom_storage, upload_to='')),
                ('image_file', models.FileField(blank=True, null=True, storage=manage_breast_screening.dicom.models.dicom_storage, upload_to='')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='dicom.series')),
            ],
            options={
                'indexes': [models.Index(fields=['sop_instance_uid'], name='dicom_image_sop_ins_c50e61_idx')],
                'constraints': [models.UniqueConstraint(fields=('instance_number', 'series'), name='unique_instance_number_per_series')],
            },
        ),
        migrations.AddIndex(
            model_name='series',
            index=models.Index(fields=['series_instance_uid'], name='dicom_serie_series__112155_idx'),
        ),
        migrations.AddConstraint(
            model_name='series',
            constraint=models.UniqueConstraint(fields=('series_number', 'study'), name='unique_series_number_per_study'),
        ),
    ]
