# Generated by Django 5.2.8 on 2026-01-22 13:18

import django.db.models.deletion
import manage_breast_screening.dicom.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_instance_uid', models.CharField(max_length=128, unique=True)),
                ('modality', models.CharField(blank=True, max_length=16)),
                ('series_number', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_instance_uid', models.CharField(max_length=128, unique=True)),
                ('source_message_id', models.CharField(max_length=128)),
                ('patient_id', models.CharField(blank=True, max_length=10)),
                ('date_and_time', models.DateTimeField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sop_instance_uid', models.CharField(max_length=128, unique=True)),
                ('instance_number', models.IntegerField(blank=True, null=True)),
                ('dicom_file', models.FileField(storage=manage_breast_screening.dicom.models.dicom_storage, upload_to='')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='dicom.series')),
            ],
        ),
        migrations.AddField(
            model_name='series',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='dicom.study'),
        ),
    ]
