# Generated by Django 6.0.2 on 2026-02-12 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='laterality',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
