# Generated by Django 6.0.2 on 2026-02-16 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom', '0002_image_laterality'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='view_position',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
