# Generated by Django 6.0.2 on 2026-02-26 16:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom', '0004_remove_image_unique_instance_number_per_series_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='repeat_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='repeat_reasons',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('PATIENT_MOVED', 'Patient moved during exposure'), ('UNABLE_COMPRESSION', 'Unable to maintain compression'), ('INADEQUATE_COMPRESSION', 'Inadequate compression achieved'), ('INCORRECT_POSITIONING', 'Incorrect positioning identified'), ('IMAGE_TOO_LIGHT', 'Image too light - exposure needs adjustment'), ('IMAGE_TOO_DARK', 'Image too dark - exposure needs adjustment'), ('MOTION_BLUR', 'Motion blur affecting image quality'), ('EQUIPMENT_FAULT', 'Equipment technical fault'), ('FOLDED_SKIN', 'Folded skin needs smoothing'), ('PECTORAL_MUSCLE', 'Pectoral muscle not visualised correctly'), ('OTHER', 'Other')], max_length=30), blank=True, default=list),
        ),
        migrations.AddField(
            model_name='series',
            name='repeat_type',
            field=models.CharField(blank=True, choices=[('ALL_REPEATS', 'All additional images were repeats'), ('SOME_REPEATS', 'Some were repeats, some were extra images'), ('NO_REPEATS', 'No repeats - all extra images were needed')], max_length=20, null=True),
        ),
    ]
