# Generated by Django 6.0.3 on 2026-03-16 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom', '0004_remove_image_unique_instance_number_per_series_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='implant_present',
            field=models.BooleanField(default=False),
        ),
    ]
