# Generated by Django 6.0.3 on 2026-03-31 10:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom', '0005_image_implant_present'),
    ]

    operations = [
        migrations.RunSQL(
            [
                "TRUNCATE TABLE dicom_image CASCADE",
                "TRUNCATE TABLE dicom_series CASCADE",
                "TRUNCATE TABLE dicom_study CASCADE",
            ]
        ),
        migrations.RemoveField(
            model_name='image',
            name='id',
        ),
        migrations.RemoveField(
            model_name='image',
            name='series',
        ),
        migrations.RemoveField(
            model_name='series',
            name='id',
        ),
        migrations.RemoveField(
            model_name='series',
            name='study',
        ),
        migrations.RemoveField(
            model_name='study',
            name='id',
        ),
        migrations.AddField(
            model_name='image',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='series',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='study',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='image',
            name='series',
            field=models.ForeignKey(
                on_delete=models.deletion.CASCADE,
                to="dicom.series",
                related_name="images",
            ),
        ),
        migrations.AddField(
            model_name='series',
            name='study',
            field=models.ForeignKey(
                on_delete=models.deletion.CASCADE,
                to="dicom.study",
                related_name="series",
            ),
        ),
    ]
