# Generated by Django 6.0.3 on 2026-03-30 14:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom', '0006_alter_image_id_alter_series_id_alter_study_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='repeat_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='repeat_reasons',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('PATIENT_MOVED', 'Participant movement'), ('UNABLE_COMPRESSION', 'Compression issues'), ('POSITIONING_ERROR', 'Positioning error'), ('POOR_EXPOSURE', 'Poor exposure (image too light or dark)'), ('ARTEFACT_OBSCURE', 'Artefacts obscuring image'), ('TECHNICAL_FAULT', 'Technical Fault'), ('OTHER', 'Other')], max_length=30), blank=True, default=list),
        ),
        migrations.AddField(
            model_name='series',
            name='repeat_type',
            field=models.CharField(blank=True, choices=[('ALL_REPEATS', 'All additional images were repeats'), ('SOME_REPEATS', 'Some were repeats, some were extra images'), ('NO_REPEATS', 'No repeats - all extra images were needed')], max_length=20, null=True),
        ),
    ]
