# Generated by Django 6.0.2 on 2026-02-19 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_groups_remove_user_is_superuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_sysadmin',
            field=models.BooleanField(default=False, help_text='Grants access to system-wide settings across all providers.'),
        ),
    ]
