# Generated by Django 6.0.3 on 2026-03-09 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_add_is_sysadmin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_sysadmin',
            new_name='is_superuser',
        ),
    ]
