ENV_CONFIG=ahl
ENVIRONMENT=ahl
AZURE_SUBSCRIPTION="Digital Screening DToS - Core Services Dev"
HUB_SUBSCRIPTION="Digital Screening DToS - DevOps"
HUB=dev
TERRAFORM_MODULES_REF=main
ENABLE_SOFT_DELETE=false
