name: manage-breast-screening-notifications

services:

  azurite:
    container_name: azurite
    command: "azurite --loose --skipApiVersionCheck --blobHost 0.0.0.0 --blobPort 10000 --queueHost 0.0.0.0 --queuePort 10001"
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - 10000:10000
      - 10001:10001
      - 10002:10002
    profiles:
      - development
      - integration

  mesh-sandbox:
    build:
      context: https://github.com/NHSDigital/mesh-sandbox.git#refs/tags/v1.0.4
    ports:
      - "8700:80"
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    healthcheck:
      test: curl -ksf http://localhost/health || exit 1
      interval: 3s
      timeout: 10s
    environment:
      - SHARED_KEY=TestKey
      - SSL=no
      - AUTH_MODE=none
      - STORE_MODE=memory
    profiles:
      - development
      - integration
    volumes:
      - ./store/mailboxes.jsonl:/app/mesh_sandbox/store/data/mailboxes.jsonl:ro
      - ./store/workflows.jsonl:/app/mesh_sandbox/store/data/workflows.jsonl:ro

  notify-api-stub:
    build:
      context: ./tests/dependencies/notify_api_stub
      dockerfile: Dockerfile
    container_name: notify_api_stub
    profiles:
      - development
      - integration
    ports:
      - "8888:8888"
    healthcheck:
      test: curl -f http://localhost:8888/health || exit 1
      interval: 3s
      timeout: 10s

  test-dependencies:
    image: alpine
    depends_on:
      azurite:
        condition: service_started
      mesh-sandbox:
        condition: service_healthy
      notify-api-stub:
        condition: service_healthy
    profiles:
        - integration

