from django.urls import path

from .views import (
    appointment_views,
    benign_lump_history_item_views,
    breast_augmentation_history_views,
    breast_cancer_history_views,
    cyst_history_view,
    implanted_medical_device_history_view,
    mastectomy_or_lumpectomy_history_view,
    special_appointment_views,
    symptom_views,
)

app_name = "mammograms"

urlpatterns = [
    path(
        "<uuid:pk>/check-in/",
        appointment_views.check_in,
        name="check_in",
    ),
    path(
        "<uuid:pk>/start-appointment/",
        appointment_views.start_appointment,
        name="start_appointment",
    ),
    path(
        "<uuid:pk>/",
        appointment_views.ShowAppointment.as_view(),
        name="show_appointment",
    ),
    path(
        "<uuid:pk>/participant/",
        appointment_views.ParticipantDetails.as_view(),
        name="participant_details",
    ),
    path(
        "<uuid:pk>/confirm-identity/",
        appointment_views.ConfirmIdentity.as_view(),
        name="confirm_identity",
    ),
    path(
        "<uuid:pk>/ask-for-medical-information/",
        appointment_views.AskForMedicalInformation.as_view(),
        name="ask_for_medical_information",
    ),
    path(
        "<uuid:pk>/record-medical-information/",
        appointment_views.RecordMedicalInformation.as_view(),
        name="record_medical_information",
    ),
    path(
        "<uuid:pk>/awaiting-images/",
        appointment_views.AwaitingImages.as_view(),
        name="awaiting_images",
    ),
    path(
        "<uuid:pk>/cannot-go-ahead/",
        appointment_views.AppointmentCannotGoAhead.as_view(),
        name="appointment_cannot_go_ahead",
    ),
    path(
        "<uuid:pk>/special-appointment/",
        special_appointment_views.ProvideSpecialAppointmentDetails.as_view(),
        name="provide_special_appointment_details",
    ),
    path(
        "<uuid:pk>/special-appointment/which-reasons/",
        special_appointment_views.MarkReasonsTemporary.as_view(),
        name="mark_reasons_temporary",
    ),
    path(
        "<uuid:pk>/record-medical-information/lump/",
        symptom_views.AddLumpView.as_view(),
        name="add_symptom_lump",
    ),
    path(
        "<uuid:pk>/record-medical-information/lump/<uuid:symptom_pk>/",
        symptom_views.ChangeLumpView.as_view(),
        name="change_symptom_lump",
    ),
    path(
        "<uuid:pk>/record-medical-information/swelling-or-shape-change/",
        symptom_views.AddSwellingOrShapeChangeView.as_view(),
        name="add_symptom_swelling_or_shape_change",
    ),
    path(
        "<uuid:pk>/record-medical-information/swelling-or-shape-change/<uuid:symptom_pk>/",
        symptom_views.ChangeSwellingOrShapeChangeView.as_view(),
        name="change_symptom_swelling_or_shape_change",
    ),
    path(
        "<uuid:pk>/record-medical-information/skin-change/",
        symptom_views.AddSkinChangeView.as_view(),
        name="add_symptom_skin_change",
    ),
    path(
        "<uuid:pk>/record-medical-information/skin-change/<uuid:symptom_pk>/",
        symptom_views.ChangeSkinChangeView.as_view(),
        name="change_symptom_skin_change",
    ),
    path(
        "<uuid:pk>/record-medical-information/nipple-change/",
        symptom_views.AddNippleChangeView.as_view(),
        name="add_symptom_nipple_change",
    ),
    path(
        "<uuid:pk>/record-medical-information/nipple-change/<uuid:symptom_pk>/",
        symptom_views.ChangeNippleChangeView.as_view(),
        name="change_symptom_nipple_change",
    ),
    path(
        "<uuid:pk>/record-medical-information/other/",
        symptom_views.AddOtherSymptomView.as_view(),
        name="add_symptom_other",
    ),
    path(
        "<uuid:pk>/record-medical-information/other/<uuid:symptom_pk>/",
        symptom_views.ChangeOtherSymptomView.as_view(),
        name="change_symptom_other",
    ),
    path(
        "<uuid:pk>/record-medical-information/delete_symptom/<uuid:symptom_pk>/",
        symptom_views.DeleteSymptomView.as_view(),
        name="delete_symptom",
    ),
    path(
        "<uuid:pk>/record-medical-information/breast-cancer-history/",
        breast_cancer_history_views.AddBreastCancerHistoryView.as_view(),
        name="add_breast_cancer_history_item",
    ),
    path(
        "<uuid:pk>/record-medical-information/breast-cancer-history/<uuid:history_item_pk>",
        breast_cancer_history_views.ChangeBreastCancerHistoryView.as_view(),
        name="change_breast_cancer_history_item",
    ),
    path(
        "<uuid:pk>/record-medical-information/breast-cancer-history/<uuid:history_item_pk>/delete",
        breast_cancer_history_views.DeleteBreastCancerHistoryView.as_view(),
        name="delete_breast_cancer_history_item",
    ),
    path(
        "<uuid:pk>/record-medical-information/implanted-medical-device-history/",
        implanted_medical_device_history_view.AddImplantedMedicalDeviceHistoryView.as_view(),
        name="add_implanted_medical_device_history_item",
    ),
    path(
        "<uuid:pk>/record-medical-information/implanted-medical-device-history/<uuid:history_item_pk>",
        implanted_medical_device_history_view.ChangeImplantedMedicalDeviceHistoryView.as_view(),
        name="change_implanted_medical_device_history_item",
    ),
    path(
        "<uuid:pk>/record-medical-information/cyst-history/",
        cyst_history_view.AddCystHistoryView.as_view(),
        name="add_cyst_history_item",
    ),
    path(
        "<uuid:pk>/record-medical-information/cyst-history/<uuid:history_item_pk>",
        cyst_history_view.ChangeCystHistoryView.as_view(),
        name="change_cyst_history_item",
    ),
    path(
        "<uuid:pk>/record-medical-information/breast-augmentation-history/",
        breast_augmentation_history_views.AddBreastAugmentationHistoryView.as_view(),
        name="add_breast_augmentation_history_item",
    ),
    path(
        "<uuid:pk>/record-medical-information/breast-augmentation-history/<uuid:history_item_pk>",
        breast_augmentation_history_views.ChangeBreastAugmentationHistoryView.as_view(),
        name="change_breast_augmentation_history_item",
    ),
    path(
        "<uuid:pk>/record-medical-information/benign-lump-history/",
        benign_lump_history_item_views.AddBenignLumpHistoryItemView.as_view(),
        name="add_benign_lump_history_item",
    ),
    path(
        "<uuid:pk>/record-medical-information/benign-lump-history/<uuid:history_item_pk>/",
        benign_lump_history_item_views.UpdateBenignLumpHistoryItemView.as_view(),
        name="change_benign_lump_history_item",
    ),
    path(
        "<uuid:pk>/record-medical-information/mastectomy-or-lumpectomy-history/",
        mastectomy_or_lumpectomy_history_view.AddMastectomyOrLumpectomyHistoryView.as_view(),
        name="add_mastectomy_or_lumpectomy_history_item",
    ),
    path(
        "<uuid:pk>/record-medical-information/mastectomy-or-lumpectomy-history/<uuid:history_item_pk>",
        mastectomy_or_lumpectomy_history_view.UpdateMastectomyOrLumpectomyHistoryView.as_view(),
        name="change_mastectomy_or_lumpectomy_history_item",
    ),
]
