ENV_CONFIG=review
AZURE_SUBSCRIPTION="Digital Screening DToS - Core Services Dev"
HUB_SUBSCRIPTION="Digital Screening DToS - DevOps"
HUB=dev
TERRAFORM_MODULES_REF=main
ENABLE_SOFT_DELETE=false
ADO_MANAGEMENT_POOL=private-pool-dev-uks
RUN_NOTIFICATIONS_SMOKE_TEST=false
