# Generated by Django 6.0.4 on 2026-04-09 13:22

import uuid

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('clinics', '0001_initial'), ('clinics', '0002_rename_setting_id_clinic_setting_and_more'), ('clinics', '0003_alter_clinic_created_at_alter_clinicslot_clinic_and_more'), ('clinics', '0004_clinic_risk_type_alter_clinic_type'), ('clinics', '0005_screeningepisode_appointment'), ('clinics', '0006_alter_appointment_status'), ('clinics', '0007_appointment_reinvite'), ('clinics', '0008_appointment_stopped_reasons'), ('clinics', '0007_alter_appointment_status'), ('clinics', '0009_merge_20250514_1140'), ('clinics', '0010_introduce_uuid_fields'), ('clinics', '0011_recreate_participants_linkage'), ('clinics', '0012_remove_screeningepisode_participant_and_more'), ('clinics', '0013_move_clinic_state_to_table'), ('clinics', '0013_alter_clinic_setting_alter_clinicslot_clinic_and_more'), ('clinics', '0014_merge_20250620_1113'), ('clinics', '0015_userassignment'), ('clinics', '0016_alter_userassignment_provider_and_more'), ('clinics', '0017_alter_userassignment_options'), ('clinics', '0018_userassignment_roles'), ('clinics', '0019_alter_clinic_type'), ('clinics', '0020_add_provider_config'), ('clinics', '0021_alter_clinicstatus_options')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.TextField()),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinics.provider')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('type', models.CharField(choices=[('SCREENING', 'Screening')], max_length=50)),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinics.setting')),
                ('risk_type', models.CharField(choices=[('MIXED_RISK', 'Mixed risk'), ('ROUTINE_RISK', 'Routine risk'), ('MOBILE', 'Mobile screening')], max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClinicSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('starts_at', models.DateTimeField()),
                ('duration_in_minutes', models.IntegerField()),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clinic_slots', to='clinics.clinic')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClinicStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In progress'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], max_length=50)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='statuses', to='clinics.clinic')),
            ],
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Clinic statuses'},
        ),
        migrations.CreateModel(
            name='UserAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='clinics.provider')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to=settings.AUTH_USER_MODEL)),
                ('roles', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Clinical', 'Clinical'), ('Administrative', 'Administrative')], max_length=32), default=list, help_text='Roles granted to the user for this provider.', validators=[django.core.validators.MinLengthValidator(1)])),
            ],
            options={
                'verbose_name': 'User provider assignment',
                'verbose_name_plural': 'User provider assignments',
                'unique_together': {('user', 'provider')},
            },
        ),
        migrations.CreateModel(
            name='ProviderConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manual_image_collection', models.BooleanField(default=True, help_text='If enabled, staff confirm images were taken without gateway integration. If disabled, images are received automatically via gateway.')),
                ('provider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='clinics.provider')),
            ],
            options={
                'verbose_name': 'Provider configuration',
                'verbose_name_plural': 'Provider configurations',
            },
        )
    ]
