# Generated by Django 5.2.1 on 2025-05-28 15:52
# Modified for Django 6 compatibility: DROP COLUMN no longer uses CASCADE by default

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinics", "0009_merge_20250514_1140"),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                "TRUNCATE TABLE clinics_provider CASCADE",
                "TRUNCATE TABLE clinics_screeningepisode CASCADE",
            ],
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Django 6 no longer uses CASCADE when dropping columns, so use explicit SQL
        # Drop all columns that have dependencies using CASCADE
        migrations.RunSQL(
            sql="ALTER TABLE clinics_provider DROP COLUMN id CASCADE",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="ALTER TABLE clinics_setting DROP COLUMN id CASCADE",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="ALTER TABLE clinics_setting DROP COLUMN IF EXISTS provider_id CASCADE",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="ALTER TABLE clinics_clinic DROP COLUMN id CASCADE",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="ALTER TABLE clinics_clinic DROP COLUMN IF EXISTS setting_id CASCADE",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="ALTER TABLE clinics_clinicslot DROP COLUMN id CASCADE",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="ALTER TABLE clinics_clinicslot DROP COLUMN IF EXISTS clinic_id CASCADE",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="ALTER TABLE clinics_screeningepisode DROP COLUMN id CASCADE",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="ALTER TABLE clinics_screeningepisode DROP COLUMN IF EXISTS participant_id CASCADE",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="ALTER TABLE clinics_appointment DROP COLUMN id CASCADE",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="ALTER TABLE clinics_appointment DROP COLUMN IF EXISTS clinic_slot_id CASCADE",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="ALTER TABLE clinics_appointment DROP COLUMN IF EXISTS screening_episode_id CASCADE",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AddField(
            model_name="provider",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AddField(
            model_name="setting",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AddField(
            model_name="setting",
            name="provider",
            field=models.ForeignKey(
                on_delete=models.deletion.CASCADE,
                to="clinics.provider",
            ),
        ),
        migrations.AddField(
            model_name="clinic",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AddField(
            model_name="clinic",
            name="setting",
            field=models.ForeignKey(
                on_delete=models.deletion.CASCADE,
                to="clinics.setting",
            ),
        ),
        migrations.AddField(
            model_name="clinicslot",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AddField(
            model_name="clinicslot",
            name="clinic",
            field=models.ForeignKey(
                on_delete=models.deletion.CASCADE,
                to="clinics.clinic",
                related_name="clinic_slots",
            ),
        ),
        migrations.AddField(
            model_name="screeningepisode",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AddField(
            model_name="screeningepisode",
            name="participant",
            field=models.ForeignKey(
                on_delete=models.deletion.CASCADE, to="participants.participant"
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="screening_episode",
            field=models.ForeignKey(
                on_delete=models.deletion.CASCADE,
                to="clinics.screeningepisode",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="clinic_slot",
            field=models.ForeignKey(
                on_delete=models.deletion.CASCADE,
                to="clinics.clinicslot",
            ),
        ),
    ]
