# Generated by Django 5.2.6 on 2025-09-19 15:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0014_merge_20250620_1113'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to='clinics.provider')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='providers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Provider Assignment',
                'verbose_name_plural': 'User Provider Assignments',
                'unique_together': {('user', 'provider')},
            },
        ),
    ]
