# Generated by Django 5.2.6 on 2025-09-24 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0016_alter_userassignment_provider_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userassignment',
            options={'verbose_name': 'User provider assignment', 'verbose_name_plural': 'User provider assignments'},
        ),
    ]
