# Generated by Django 5.2.6 on 2025-09-29 14:01

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0017_alter_userassignment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='userassignment',
            name='roles',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Clinical', 'Clinical'), ('Administrative', 'Administrative')], max_length=32), default=list, help_text='Roles granted to the user for this provider.', size=None, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
