# Generated by Django 6.0.1 on 2026-01-28 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0018_userassignment_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='type',
            field=models.CharField(choices=[('SCREENING', 'Screening')], max_length=50),
        ),
    ]
