# Generated by Django 5.2.8 on 2025-12-12 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0018_userassignment_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicslot',
            name='starts_at',
            field=models.TimeField(),
        ),
    ]
