# Generated by Django 5.2.8 on 2025-12-15 13:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0018_userassignment_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicslot',
            name='starts_at_time',
            field=models.TimeField(default=datetime.time(13, 59, 56, 682231)),
            preserve_default=False,
        ),
    ]
