# Generated by Django 6.0.2 on 2026-02-19 11:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0019_alter_clinic_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manual_image_collection', models.BooleanField(default=True, help_text='If enabled, staff confirm images were taken without gateway integration. If disabled, images are received automatically via gateway.')),
                ('provider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='clinics.provider')),
            ],
            options={
                'verbose_name': 'Provider configuration',
                'verbose_name_plural': 'Provider configurations',
            },
        ),
    ]
