# Generated by Django 6.0.3 on 2026-03-17 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0020_add_provider_config'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clinicstatus',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Clinic statuses'},
        ),
    ]
