# Generated by Django 5.2.3 on 2025-07-08 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_appointment_created_at_alter_clinic_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='bso_code',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='messagebatch',
            name='routing_plan_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
