# Generated by Django 5.2.3 on 2025-08-05 08:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_clinic_bso_code_messagebatch_routing_plan_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
                ('idempotency_key', models.CharField(max_length=150)),
                ('status_updated_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='notifications.message')),
            ],
        ),
        migrations.CreateModel(
            name='MessageStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
                ('idempotency_key', models.CharField(max_length=150)),
                ('status_updated_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='notifications.message')),
            ],
        ),
    ]
