# Generated by Django 5.2.3 on 2025-07-31 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_clinic_bso_code_messagebatch_routing_plan_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='nbss_id',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
