# Generated by Django 5.2.3 on 2025-08-01 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_clinic_bso_code_messagebatch_routing_plan_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='address_description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
