# Generated by Django 5.2.3 on 2025-08-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_alter_appointment_nbss_id_to_unique_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='cancelled_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
