# Generated by Django 5.2.3 on 2025-08-01 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_alter_clinic_add_latlong'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='personalisation',
            field=models.JSONField(null=True),
        ),
    ]
