# Generated by Django 5.2.3 on 2025-08-13 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_alter_message_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelstatus',
            name='status',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('cancelled', 'Cancelled'), ('delivered', 'Delivered'), ('notification_attempted', 'Notification Attempted'), ('notified', 'Notified'), ('pending_virus_check', 'Pending Virus Check'), ('read', 'Read'), ('received', 'Received'), ('rejected', 'Rejected'), ('permanent_failure', 'Permanent Failure'), ('technical_failure', 'Technical Failure'), ('temporary_failure', 'Temporary Failure'), ('unknown', 'Unknown'), ('unnotified', 'Unnotified'), ('validation_failed', 'Validation Failed')], max_length=50),
        ),
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('delivered', 'Delivered'), ('enriched', 'Endriched'), ('failed', 'Failed'), ('pending_enrichment', 'Pending Enrichment'), ('sending', 'Sending')], default='pending_enrichment', max_length=50),
        ),
        migrations.AlterField(
            model_name='messagestatus',
            name='status',
            field=models.CharField(choices=[('delivered', 'Delivered'), ('enriched', 'Endriched'), ('failed', 'Failed'), ('pending_enrichment', 'Pending Enrichment'), ('sending', 'Sending')], max_length=50),
        ),
    ]
