# Generated by Django 5.2.3 on 2025-08-18 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_alter_channelstatus_status_alter_message_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelstatus',
            name='idempotency_key',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='messagebatch',
            name='status',
            field=models.CharField(choices=[('failed_recoverable', 'Failed Recoverable'), ('failed_unrecoverable', 'Failed Unrecoverable'), ('scheduled', 'Scheduled'), ('sent', 'Sent'), ('unscheduled', 'Unscheduled')], default='unscheduled', max_length=50),
        ),
        migrations.AlterField(
            model_name='messagestatus',
            name='idempotency_key',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
