# Generated by Django 5.2.3 on 2025-08-19 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0010_alter_channelstatus_idempotency_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='batch_id',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='appointment',
            name='booked_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='episode_started_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='episode_type',
            field=models.CharField(choices=[('N', 'Early Recall'), ('G', 'Gp Referral'), ('F', 'Routine First Call'), ('R', 'Routine Recall'), ('S', 'Self Referral'), ('H', 'Very High Risk'), ('T', 'Vhr Short Term Recall')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('B', 'Booked'), ('C', 'Cancelled'), ('U', 'Updated')], max_length=50),
        ),
    ]
