# Generated by Django 5.2.3 on 2025-08-20 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0011_appointment_batch_id_appointment_booked_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagebatch',
            old_name='notify_errors',
            new_name='nhs_notify_errors',
        ),
    ]
