# Generated by Django 5.2.3 on 2025-08-21 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0012_alter_message_batch_notify_errors'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='blob_name',
            field=models.TextField(default='/'),
            preserve_default=False,
        ),
    ]
