# Generated by Django 5.2.3 on 2025-08-22 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0013_add_blob_name_to_appointments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='blob_name',
        ),
    ]
