# Generated by Django 5.2.3 on 2025-08-26 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0014_remove_blob_name_from_appointments'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['nbss_id'], name='notificatio_nbss_id_b218dc_idx'),
        ),
    ]
