# Generated by Django 5.2.5 on 2025-09-02 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0015_add_nbss_id_as_index_to_appointments'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='nhs_notify_errors',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
