# Generated by Django 5.2.6 on 2025-09-19 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0016_add_notify_errors_to_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='assessment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='attended_not_screened',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='appointment',
            name='completed_at',
            field=models.DateTimeField(null=True),
        ),
    ]
