# Generated by Django 5.2.5 on 2025-09-11 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0016_add_notify_errors_to_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='location_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='clinic',
            name='location_url',
            field=models.TextField(blank=True),
        ),
    ]
