# Generated by Django 5.2.6 on 2025-09-19 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0017_appointment_assessment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('B', 'Booked'), ('C', 'Cancelled'), ('A', 'Attended'), ('D', 'Dna')], max_length=50),
        ),
    ]
