# Generated by Django 5.2.6 on 2025-10-02 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0018_alter_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='number',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
