# Generated by Django 5.2.7 on 2025-10-09 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0019_alter_appointment_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AddIndex(
            model_name='clinic',
            index=models.Index(fields=['code', 'bso_code'], name='notificatio_code_55dbdb_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['notify_id'], name='notificatio_notify__ca989c_idx'),
        ),
        migrations.AddIndex(
            model_name='messagebatch',
            index=models.Index(fields=['notify_id'], name='notificatio_notify__cf997b_idx'),
        ),
        migrations.AddConstraint(
            model_name='clinic',
            constraint=models.UniqueConstraint(fields=('code', 'bso_code'), name='unique_code_bso_code'),
        ),
    ]
