# Generated by Django 5.2.7 on 2025-10-09 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0019_alter_appointment_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelstatus',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='messagestatus',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
