# Generated by Django 5.2.7 on 2025-11-04 14:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0021_alter_clinic_code_clinic_notificatio_code_55dbdb_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='originating_file',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=[], size=None),
        ),
    ]
