# Generated by Django 5.2.7 on 2025-11-04 14:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0022_appointment_originating_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='originating_file',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, size=None),
        ),
    ]
