# Generated by Django 6.0.1 on 2026-01-20 14:32

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('participants', '0055_rename_confirmed_to_scheduled'),
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('additional_details', models.TextField(blank=True, default='')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='participants.appointment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('view_position', models.CharField(blank=True, choices=[('CC', 'CC'), ('MLO', 'MLO'), ('EKLUND', 'EKLUND')], help_text='e.g., CC, MLO', max_length=10)),
                ('laterality', models.CharField(blank=True, choices=[('L', 'Left'), ('R', 'Right')], help_text='L or R', max_length=1)),
                ('count', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manual_images.study')),
            ],
            options={
                'unique_together': {('study', 'view_position', 'laterality')},
            },
        ),
    ]
