# Generated by Django 6.0.1 on 2026-01-27 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manual_images', '0001_initial'),
        ('participants', '0057_alter_appointmentstatus_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='participants.appointment'),
        ),
    ]
