# Generated by Django 6.0.1 on 2026-01-27 15:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manual_images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='is_repeat',
            field=models.CharField(blank=True, choices=[('YES_REPEAT', 'Yes, it was a repeat'), ('NO_EXTRA_NEEDED', 'No, an extra image was needed to capture the complete view'), ('ALL_REPEATS', 'Yes, all images were repeats'), ('SOME_REPEATS', 'Yes, some were repeats and some were extra images'), ('ALL_EXTRA', 'No, all extra images were needed to capture the complete view')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='repeat_reasons',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('PATIENT_MOVED', 'Patient moved during exposure'), ('UNABLE_COMPRESSION', 'Unable to maintain compression'), ('INADEQUATE_COMPRESSION', 'Inadequate compression achieved'), ('INCORRECT_POSITIONING', 'Incorrect positioning identified'), ('IMAGE_TOO_LIGHT', 'Image too light - exposure needs adjustment'), ('IMAGE_TOO_DARK', 'Image too dark - exposure needs adjustment'), ('MOTION_BLUR', 'Motion blur affecting image quality'), ('EQUIPMENT_FAULT', 'Equipment technical fault'), ('FOLDED_SKIN', 'Folded skin needs smoothing'), ('PECTORAL_MUSCLE', 'Pectoral muscle not visualised correctly'), ('OTHER', 'Other')], max_length=30), blank=True, default=list),
        ),
    ]
