# Generated by Django 6.0.1 on 2026-02-03 16:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manual_images", "0002_alter_study_appointment"),
    ]

    operations = [
        migrations.AddField(
            model_name="study",
            name="imperfect_but_best_possible",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="study",
            name="completeness",
            field=models.CharField(
                blank=True,
                choices=[
                    ("COMPLETE", "Complete set of images"),
                    ("PARTIAL", "Partial mammography"),
                    ("INCOMPLETE", "Incomplete set of images"),
                ],
                default="",
            ),
        ),
        migrations.AddField(
            model_name="study",
            name="reasons_incomplete",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    blank=True,
                    choices=[
                        ("CONSENT_WITHDRAWN", "Consent withdrawn"),
                        (
                            "LANGUAGE_OR_LEARNING_DIFFICULTIES",
                            "Language or learning difficulties",
                        ),
                        ("UNABLE_TO_SCAN_TISSUE", "Unable to scan tissue"),
                        ("WHEELCHAIR", "Positioning difficulties due to wheelchair"),
                        (
                            "OTHER_MOBILITY",
                            "Positioning difficulties for other mobility reasons",
                        ),
                        ("TECHNICAL_ISSUES", "Technical issues"),
                        ("OTHER", "Other"),
                    ],
                    default="",
                ),
                default=list,
            ),
        ),
        migrations.AddField(
            model_name="study",
            name="reasons_incomplete_details",
            field=models.TextField(blank=True, default=""),
        ),
    ]
