# Generated by Django 6.0.3 on 2026-03-10 14:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manual_images', '0003_add_series_repeat_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='repeat_reasons',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('PATIENT_MOVED', 'Participant movement'), ('UNABLE_COMPRESSION', 'Compression issues'), ('POSITIONING_ERROR', 'Positioning error'), ('POOR_EXPOSURE', 'Poor exposure (image too light or dark)'), ('ARTEFACT_OBSCURE', 'Artefact obscuring image'), ('TECHNICAL_FAULT', 'Technical Fault'), ('OTHER', 'Other')], max_length=30), blank=True, default=list),
        ),
    ]
