# Generated by Django 5.2.3 on 2025-08-12 10:13

from django.db import migrations


def create_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.create(name="Administrative")
    Group.objects.create(name="Clinical")
    Group.objects.create(name="Superuser")


def delete_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.filter(name="Administrative").delete()
    Group.objects.filter(name="Clinical").delete()
    Group.objects.filter(name="Superuser").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_auditlog_system_update_id_and_more_updated"),
    ]

    operations = [
        migrations.RunPython(create_groups, delete_groups),
    ]
