# Generated by Django 6.0.4 on 2026-04-09 13:43

import uuid

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import manage_breast_screening.nhsuk_forms.validators


def add_symptom_types(apps, schema_editor):
    SymptomType = apps.get_model("participants", "SymptomType")
    SymptomType.objects.get_or_create(id='BREAST_PAIN', defaults={'name': 'Breast pain'})
    SymptomType.objects.create(id="LUMP", name="Lump")
    SymptomType.objects.create(
        id="SWELLING_OR_SHAPE_CHANGE", name="Swelling or shape change"
    )
    SymptomType.objects.create(id="SKIN_CHANGE", name="Skin change")
    SymptomType.objects.create(id="NIPPLE_CHANGE", name="Nipple change")
    SymptomType.objects.create(id="OTHER", name="Other")


def remove_symptom_types(apps, schema_editor):
    SymptomType = apps.get_model("participants", "SymptomType")
    SymptomType.objects.all().delete()

def add_symptom_sub_types(apps, schema_editor):
    SymptomSubType = apps.get_model("participants", "SymptomSubType")

    SymptomSubType.objects.create(
        symptom_type_id="SKIN_CHANGE", id="SORES_OR_CYSTS", name="Sores or cysts"
    )
    SymptomSubType.objects.create(
        symptom_type_id="SKIN_CHANGE",
        id="DIMPLES_OR_INDENTATION",
        name="Dimples or indentation",
    )
    SymptomSubType.objects.create(symptom_type_id="SKIN_CHANGE", id="RASH", name="Rash")
    SymptomSubType.objects.create(
        symptom_type_id="SKIN_CHANGE", id="COLOUR_CHANGE", name="Colour change"
    )
    SymptomSubType.objects.create(
        symptom_type_id="SKIN_CHANGE", id="OTHER", name="Other"
    )

    SymptomSubType.objects.create(
        symptom_type_id="NIPPLE_CHANGE",
        id="NIPPLE_CHANGE_BLOODY_DISCHARGE",
        name="Bloody discharge",
    )
    SymptomSubType.objects.create(
        symptom_type_id="NIPPLE_CHANGE",
        id="NIPPLE_CHANGE_OTHER_DISCHARGE",
        name="Other discharge",
    )
    SymptomSubType.objects.create(
        symptom_type_id="NIPPLE_CHANGE", id="NIPPLE_CHANGE_INVERSION", name="Inversion"
    )
    SymptomSubType.objects.create(
        symptom_type_id="NIPPLE_CHANGE",
        id="NIPPLE_CHANGE_RASH_OR_ECZEMA",
        name="Rash or eczema",
    )
    SymptomSubType.objects.create(
        symptom_type_id="NIPPLE_CHANGE",
        id="NIPPLE_CHANGE_SHAPE_CHANGE",
        name="Shape change",
    )
    SymptomSubType.objects.create(
        symptom_type_id="NIPPLE_CHANGE",
        id="NIPPLE_CHANGE_COLOUR_CHANGE",
        name="Colour change",
    )
    SymptomSubType.objects.create(
        symptom_type_id="NIPPLE_CHANGE", id="NIPPLE_CHANGE_OTHER", name="Other"
    )

    SymptomSubType.objects.filter(id="OTHER").update(
        id="SKIN_CHANGE_OTHER", name="Other"
    )


def remove_symptom_sub_types(apps, schema_editor):
    SymptomSubType = apps.get_model("participants", "SymptomSubType")
    SymptomSubType.objects.all().delete()

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0001_squashed_0021_alter_clinicstatus_options'),
        ('contenttypes', '__latest__'),
        ('core', '__latest__'),
        ('users', '__latest__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField()),
                ('last_name', models.CharField()),
                ('gender', models.CharField()),
                ('nhs_number', models.CharField(unique=True, max_length=10)),
                ('phone', models.CharField()),
                ('email', models.EmailField(max_length=254)),
                ('date_of_birth', models.DateField()),
                ('risk_level', models.CharField()),
                ('extra_needs', models.JSONField(blank=True, default=list)),
                ('ethnic_background_id', models.CharField(blank=True, choices=[('english_welsh_scottish_ni_british', 'English, Welsh, Scottish, Northern Irish or British'), ('irish', 'Irish'), ('gypsy_or_irish_traveller', 'Gypsy or Irish Traveller'), ('any_other_white_background', 'Any other White background'), ('white_and_black_caribbean', 'White and Black Caribbean'), ('white_and_black_african', 'White and Black African'), ('white_and_asian', 'White and Asian'), ('any_other_mixed_or_multiple_ethnic_background', 'Any other mixed or multiple ethnic background'), ('indian', 'Indian'), ('pakistani', 'Pakistani'), ('bangladeshi', 'Bangladeshi'), ('chinese', 'Chinese'), ('any_other_asian_background', 'Any other Asian background'), ('african', 'African'), ('caribbean', 'Caribbean'), ('any_other_black_african_or_caribbean_background', 'Any other Black, African or Caribbean background'), ('arab', 'Arab'), ('any_other_ethnic_background', 'Any other ethnic group'), ('prefer_not_to_say', 'Prefer not to say')], null=True)),
                ('any_other_background_details', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ParticipantAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lines', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, size=5)),
                ('postcode', models.CharField(blank=True, null=True)),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='address', to='participants.participant')),
            ],
        ),
        migrations.CreateModel(
            name='ScreeningEpisode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='participants.participant')),
                ('protocol', models.CharField(choices=[('FAMILY_HISTORY', 'Family history')], default='FAMILY_HISTORY', max_length=50))
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reinvite', models.BooleanField(default=False)),
                ('stopped_reasons', models.JSONField(blank=True, null=True)),
                ('clinic_slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinics.clinicslot')),
                ('screening_episode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='participants.screeningepisode')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AppointmentStatus',
            fields=[
                ('name', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('CHECKED_IN', 'Checked in'), ('IN_PROGRESS', 'In progress'), ('CANCELLED', 'Cancelled'), ('DID_NOT_ATTEND', 'Did not attend'), ('SCREENED', 'Screened'), ('PARTIALLY_SCREENED', 'Partially screened'), ('ATTENDED_NOT_SCREENED', 'Attended not screened'), ('PAUSED', 'Paused')], default='SCHEDULED', max_length=50)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='statuses', to='participants.appointment')),
            ],
            options={
                'ordering': ['-created_at']
            },

        ),
        migrations.CreateModel(
            name='ParticipantReportedMammogram',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location_type', models.CharField(choices=[('SAME_PROVIDER', 'At this NHS breast screening unit'), ('ANOTHER_NHS_PROVIDER', 'At another NHS breast screening unit'), ('ELSEWHERE_UK', 'Elsewhere in the UK'), ('OUTSIDE_UK', 'Outside the UK'), ('PREFER_NOT_TO_SAY', 'Prefer not to say')])),
                ('location_details', models.TextField(blank=True, default='')),
                ('date_type', models.CharField(choices=[('EXACT', 'Enter an exact date'), ('MORE_THAN_SIX_MONTHS', 'Not sure (at least 6 months ago)'), ('LESS_THAN_SIX_MONTHS', 'Not sure (less than 6 months ago)')])),
                ('exact_date', models.DateField(blank=True, null=True)),
                ('approx_date', models.CharField(blank=True, default='')),
                ('different_name', models.CharField(blank=True, default='')),
                ('additional_information', models.TextField(blank=True, default='')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reported_mammograms', to='participants.appointment')),
                ('reason_for_continuing', models.TextField(blank=True, default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SymptomType',
            fields=[
                ('id', models.CharField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SymptomSubType',
            fields=[
                ('id', models.CharField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField()),
                ('symptom_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participants.symptomtype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reported_at', models.DateField()),
                ('description', models.CharField(blank=True)),
                ('area', models.CharField(choices=[('RIGHT_BREAST', 'Right breast'), ('LEFT_BREAST', 'Left breast'), ('BOTH_BREASTS', 'Both breasts'), ('OTHER', 'Other')])),
                ('area_description', models.CharField(blank=True)),
                ('investigated', models.BooleanField(default=False)),
                ('when_started', models.CharField(blank=True, choices=[('LESS_THAN_THREE_MONTHS', 'Less than 3 months'), ('THREE MONTHS TO A YEAR', '3 months to a year'), ('ONE_TO_THREE_YEARS', '1 to 3 years'), ('OVER_THREE_YEARS', 'Over 3 years'), ('SINCE_A_SPECIFIC_DATE', 'Since a specific date'), ('NOT_SURE', 'Not sure')])),
                ('year_started', models.IntegerField(blank=True, null=True)),
                ('month_started', models.IntegerField(blank=True, null=True)),
                ('intermittent', models.BooleanField(default=False)),
                ('recently_resolved', models.BooleanField(default=False)),
                ('when_resolved', models.CharField(blank=True)),
                ('additional_information', models.CharField(blank=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='symptoms', to='participants.appointment')),
                ('symptom_sub_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='participants.symptomsubtype')),
                ('symptom_sub_type_details', models.CharField(blank=True)),
                ('symptom_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='participants.symptomtype')),
                ('investigation_details', models.CharField(blank=True)),
            ]
        ),
        migrations.RunPython(
            code=add_symptom_types,
            reverse_code=remove_symptom_types,
        ),
        migrations.RunPython(
            code=add_symptom_sub_types,
            reverse_code=remove_symptom_sub_types,
        ),

        migrations.CreateModel(
            name='BreastAugmentationHistoryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('right_breast_procedures', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('BREAST_IMPLANTS', 'Breast implants (silicone or saline)'), ('OTHER_AUGMENTATION', 'Other augmentation'), ('NO_PROCEDURES', 'No procedures')]), default=list, validators=[manage_breast_screening.nhsuk_forms.validators.ExcludesOtherOptionsValidator('NO_PROCEDURES', 'No procedures')])),
                ('left_breast_procedures', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('BREAST_IMPLANTS', 'Breast implants (silicone or saline)'), ('OTHER_AUGMENTATION', 'Other augmentation'), ('NO_PROCEDURES', 'No procedures')]), default=list, validators=[manage_breast_screening.nhsuk_forms.validators.ExcludesOtherOptionsValidator('NO_PROCEDURES', 'No procedures')])),
                ('procedure_year', models.IntegerField(blank=True, null=True)),
                ('implants_have_been_removed', models.BooleanField()),
                ('additional_details', models.TextField(blank=True, default='')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='breast_augmentation_history_items', to='participants.appointment')),
                ('removal_year', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OtherProcedureHistoryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('procedure', models.CharField(choices=[('BREAST_REDUCTION', 'Breast reduction'), ('BREAST_SYMMETRISATION', 'Breast symmetrisation'), ('NIPPLE_CORRECTION', 'Nipple correction'), ('OTHER', 'Other')])),
                ('procedure_details', models.CharField(blank=True, default='')),
                ('procedure_year', models.IntegerField(null=True)),
                ('additional_details', models.TextField(blank=True, default='')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='other_procedure_history_items', to='participants.appointment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BenignLumpHistoryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('right_breast_procedures', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('NEEDLE_BIOPSY', 'Needle biopsy'), ('LUMP_REMOVED', 'Lump removed'), ('NO_PROCEDURES', 'No procedures')]), default=list)),
                ('left_breast_procedures', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('NEEDLE_BIOPSY', 'Needle biopsy'), ('LUMP_REMOVED', 'Lump removed'), ('NO_PROCEDURES', 'No procedures')]), default=list)),
                ('procedure_year', models.IntegerField(null=True)),
                ('procedure_location', models.CharField(choices=[('NHS_HOSPITAL', 'At an NHS hospital'), ('PRIVATE_CLINIC_UK', 'At a private clinic in the UK'), ('OUTSIDE_UK', 'Outside the UK'), ('MULTIPLE_LOCATIONS', 'In multiple locations'), ('EXACT_LOCATION_UNKNOWN', 'Exact location unknown')])),
                ('procedure_location_details', models.CharField(blank=True, default='')),
                ('additional_details', models.TextField(blank=True, default='')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='benign_lump_history_items', to='participants.appointment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MastectomyOrLumpectomyHistoryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('right_breast_procedure', models.CharField(choices=[('LUMPECTOMY', 'Lumpectomy'), ('MASTECTOMY_TISSUE_REMAINING', 'Mastectomy (tissue remaining)'), ('MASTECTOMY_NO_TISSUE_REMAINING', 'Mastectomy (no tissue remaining)'), ('NO_PROCEDURE', 'No procedure')])),
                ('left_breast_procedure', models.CharField(choices=[('LUMPECTOMY', 'Lumpectomy'), ('MASTECTOMY_TISSUE_REMAINING', 'Mastectomy (tissue remaining)'), ('MASTECTOMY_NO_TISSUE_REMAINING', 'Mastectomy (no tissue remaining)'), ('NO_PROCEDURE', 'No procedure')])),
                ('right_breast_other_surgery', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('RECONSTRUCTION', 'Reconstruction'), ('SYMMETRISATION', 'Symmetrisation'), ('NO_OTHER_SURGERY', 'No other surgery')]), default=list)),
                ('left_breast_other_surgery', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('RECONSTRUCTION', 'Reconstruction'), ('SYMMETRISATION', 'Symmetrisation'), ('NO_OTHER_SURGERY', 'No other surgery')]), default=list)),
                ('year_of_surgery', models.IntegerField(blank=True, null=True)),
                ('surgery_reason', models.CharField(choices=[('RISK_REDUCTION', 'Risk reduction'), ('GENDER_AFFIRMATION', 'Gender-affirmation (top surgery)'), ('OTHER_REASON', 'Other reason')])),
                ('surgery_other_reason_details', models.CharField(blank=True, default='')),
                ('additional_details', models.TextField(blank=True, default='')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mastectomy_or_lumpectomy_history_items', to='participants.appointment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CystHistoryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('treatment', models.CharField(choices=[('DRAINAGE_OR_REMOVAL', 'Drainage or removal'), ('NO_TREATMENT', 'No treatment')])),
                ('additional_details', models.TextField(blank=True, default='')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cyst_history_items', to='participants.appointment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImplantedMedicalDeviceHistoryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.CharField(choices=[('CARDIAC_DEVICE', 'Cardiac device (such as a pacemaker or ICD)'), ('HICKMAN_LINE', 'Hickman line'), ('OTHER_MEDICAL_DEVICE', 'Other medical device (or does not know)')])),
                ('device_has_been_removed', models.BooleanField()),
                ('other_medical_device_details', models.CharField(blank=True, default='')),
                ('procedure_year', models.IntegerField(null=True)),
                ('removal_year', models.IntegerField(null=True)),
                ('additional_details', models.TextField(blank=True, default='')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='implanted_medical_device_history_items', to='participants.appointment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BreastCancerHistoryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diagnosis_location', models.CharField(choices=[('RIGHT_BREAST', 'Right breast'), ('LEFT_BREAST', 'Left breast'), ('BOTH_BREASTS', 'Both breasts'), ('DONT_KNOW', "Don't know")])),
                ('diagnosis_year', models.IntegerField(blank=True, null=True)),
                ('left_breast_procedure', models.CharField(choices=[('LUMPECTOMY', 'Lumpectomy'), ('MASTECTOMY_TISSUE_REMAINING', 'Mastectomy (tissue remaining)'), ('MASTECTOMY_NO_TISSUE_REMAINING', 'Mastectomy (no tissue remaining)'), ('NO_PROCEDURE', 'No procedure')])),
                ('right_breast_procedure', models.CharField(choices=[('LUMPECTOMY', 'Lumpectomy'), ('MASTECTOMY_TISSUE_REMAINING', 'Mastectomy (tissue remaining)'), ('MASTECTOMY_NO_TISSUE_REMAINING', 'Mastectomy (no tissue remaining)'), ('NO_PROCEDURE', 'No procedure')])),
                ('left_breast_other_surgery', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('LYMPH_NODE_SURGERY', 'Lymph node surgery'), ('RECONSTRUCTION', 'Reconstruction'), ('SYMMETRISATION', 'Symmetrisation'), ('NO_SURGERY', 'No other surgery')]), default=list, validators=[manage_breast_screening.nhsuk_forms.validators.ExcludesOtherOptionsValidator('NO_SURGERY', 'No other surgery')])),
                ('right_breast_other_surgery', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('LYMPH_NODE_SURGERY', 'Lymph node surgery'), ('RECONSTRUCTION', 'Reconstruction'), ('SYMMETRISATION', 'Symmetrisation'), ('NO_SURGERY', 'No other surgery')]), default=list, validators=[manage_breast_screening.nhsuk_forms.validators.ExcludesOtherOptionsValidator('NO_SURGERY', 'No other surgery')])),
                ('left_breast_treatment', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('BREAST_RADIOTHERAPY', 'Breast radiotherapy'), ('LYMPH_NODE_RADIOTHERAPY', 'Lymph node radiotherapy'), ('NO_RADIOTHERAPY', 'No radiotherapy')]), default=list, validators=[manage_breast_screening.nhsuk_forms.validators.ExcludesOtherOptionsValidator('NO_RADIOTHERAPY', 'No radiotherapy')])),
                ('right_breast_treatment', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('BREAST_RADIOTHERAPY', 'Breast radiotherapy'), ('LYMPH_NODE_RADIOTHERAPY', 'Lymph node radiotherapy'), ('NO_RADIOTHERAPY', 'No radiotherapy')]), default=list, validators=[manage_breast_screening.nhsuk_forms.validators.ExcludesOtherOptionsValidator('NO_RADIOTHERAPY', 'No radiotherapy')])),
                ('systemic_treatments', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('CHEMOTHERAPY', 'Chemotherapy'), ('HORMONE_THERAPY', 'Hormone therapy'), ('OTHER', 'Other'), ('NO_SYSTEMIC_TREATMENTS', 'No systemic treatments')]), default=list, validators=[manage_breast_screening.nhsuk_forms.validators.ExcludesOtherOptionsValidator('NO_SYSTEMIC_TREATMENTS', 'No systemic treatments')])),
                ('systemic_treatments_other_treatment_details', models.CharField(blank=True, default='')),
                ('intervention_location', models.CharField(choices=[('NHS_HOSPITAL', 'At an NHS hospital'), ('PRIVATE_CLINIC_UK', 'At a private clinic in the UK'), ('OUTSIDE_UK', 'Outside the UK'), ('MULTIPLE_LOCATIONS', 'In multiple locations'), ('EXACT_LOCATION_UNKNOWN', 'Exact location unknown')])),
                ('intervention_location_details', models.CharField(blank=True, default='')),
                ('additional_details', models.TextField(blank=True, default='')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='breast_cancer_history_items', to='participants.appointment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AppointmentNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(blank=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='note', to='participants.appointment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MedicalInformationReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.CharField(choices=[('MAMMOGRAM_HISTORY', 'Mammogram history'), ('SYMPTOMS', 'Symptoms'), ('MEDICAL_HISTORY', 'Medical history'), ('BREAST_FEATURES', 'Breast features'), ('OTHER_INFORMATION', 'Other information')], max_length=50)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medical_information_reviews', to='participants.appointment')),
                ('reviewed_by', models.ForeignKey(help_text='The user who marked this section as reviewed', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['appointment', 'section'], name='participant_appoint_1c0272_idx')],
                'unique_together': {('appointment', 'section')},
            },
        ),
        migrations.CreateModel(
            name='AppointmentWorkflowStepCompletion',
            fields=[
                ('step_name', models.CharField(choices=[('CONFIRM_IDENTITY', 'Confirm identity'), ('REVIEW_MEDICAL_INFORMATION', 'Review medical information'), ('TAKE_IMAGES', 'Take images'), ('CHECK_INFORMATION', 'Check information')], max_length=50)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='completed_workflow_steps', to='participants.appointment')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BreastFeatureAnnotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('annotations_json', models.JSONField(default=list)),
                ('diagram_version', models.IntegerField(default=1)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='breast_features', to='participants.appointment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HormoneReplacementTherapy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('YES', 'Yes'), ('NO_BUT_STOPPED_RECENTLY', 'No, but stopped recently'), ('NO', 'No')])),
                ('approx_start_date', models.CharField(blank=True, default='')),
                ('approx_end_date', models.CharField(blank=True, default='')),
                ('approx_previous_duration', models.CharField(blank=True, default='')),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='hormone_replacement_therapy', to='participants.appointment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PregnancyAndBreastfeeding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pregnancy_status', models.CharField(choices=[('YES', 'Yes'), ('NO_BUT_HAS_BEEN_RECENTLY', 'No, but has been recently'), ('NO', 'No')])),
                ('approx_pregnancy_due_date', models.CharField(blank=True, default='')),
                ('approx_pregnancy_end_date', models.CharField(blank=True, default='')),
                ('breastfeeding_status', models.CharField(choices=[('YES', 'Yes'), ('NO_BUT_STOPPED_RECENTLY', 'No, but stopped recently'), ('NO', 'No')])),
                ('approx_breastfeeding_start_date', models.CharField(blank=True, default='')),
                ('approx_breastfeeding_end_date', models.CharField(choices=[('YES', 'Yes'), ('NO_BUT_STOPPED_RECENTLY', 'No, but stopped recently'), ('NO', 'No')])),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='pregnancy_and_breastfeeding', to='participants.appointment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OtherMedicalInformation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('details', models.TextField(blank=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='other_medical_information', to='participants.appointment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConfirmedPreviousMammogram',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location_details', models.TextField(blank=True, default='')),
                ('exact_date', models.DateField()),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_previous_mammograms', to='participants.participant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
