# Generated by Django 5.2.1 on 2025-05-28 15:52
# Modified for Django 6 compatibility: DROP COLUMN no longer uses CASCADE by default

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("participants", "0006_remove_participant_ethnicity_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            sql="TRUNCATE TABLE participants_participant CASCADE",
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Django 6 no longer uses CASCADE when dropping columns, so use explicit SQL
        migrations.RunSQL(
            sql="ALTER TABLE participants_participant DROP COLUMN id CASCADE",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AddField(
            model_name="participant",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
