# Generated by Django 5.2.3 on 2025-07-08 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0016_participant_any_other_background_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='screeningepisode',
            name='protocol',
            field=models.CharField(choices=[('FAMILY_HISTORY', 'Family history')], default='FAMILY_HISTORY', max_length=50),
        ),
    ]
