# Generated by Django 5.2.3 on 2025-07-07 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0016_participant_any_other_background_details'),
        ('participants', '0016_participantreportedmammogram'),
    ]

    operations = [
    ]
