# Generated by Django 5.2.3 on 2025-07-08 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0017_merge_20250707_0856'),
        ('participants', '0017_screeningepisode_protocol'),
    ]

    operations = [
    ]
