# Generated by Django 5.2.3 on 2025-08-14 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0018_merge_20250708_1015'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'permissions': [('perform_apppointment', 'Perform mammogram appointment')]},
        ),
    ]
