# Generated by Django 5.2.5 on 2025-09-04 15:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0018_merge_20250708_1015'),
    ]

    operations = [
        migrations.CreateModel(
            name='SymptomType',
            fields=[
                ('id', models.CharField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SymptomSubType',
            fields=[
                ('id', models.CharField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField()),
                ('symptom_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participants.symptomtype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ParticipantReportedSymptom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reported_at', models.DateField()),
                ('description', models.CharField(blank=True)),
                ('area', models.CharField(choices=[('RIGHT_BREAST', 'Right'), ('LEFT_BREAST', 'Left'), ('BOTH_BREASTS', 'Both'), ('OTHER', 'Other')])),
                ('area_description', models.CharField(blank=True)),
                ('investigated', models.BooleanField()),
                ('when_started', models.CharField(blank=True)),
                ('year_started', models.IntegerField(blank=True, null=True)),
                ('month_started', models.IntegerField(blank=True, null=True)),
                ('intermittent', models.BooleanField(default=False)),
                ('recently_resolved', models.BooleanField(default=False)),
                ('when_resolved', models.CharField(blank=True)),
                ('additional_information', models.CharField(blank=True)),
                ('appointment_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='participants.appointment')),
                ('participant_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='participants.participant')),
                ('symptom_sub_type_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='participants.symptomsubtype')),
                ('symptom_type_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='participants.symptomtype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
