# Generated by Django 5.2.5 on 2025-09-08 09:55

from django.db import migrations


def add_symptom_types(apps, schema_editor):
    SymptomType = apps.get_model("participants", "SymptomType")
    SymptomType.objects.create(id="lump", name="Lump")
    SymptomType.objects.create(
        id="swelling-or-shape-change", name="Swelling or shape change"
    )
    SymptomType.objects.create(id="skin-change", name="Skin change")
    SymptomType.objects.create(id="nipple-change", name="Nipple change")
    SymptomType.objects.create(id="other", name="Other")


def remove_symptom_types(apps, schema_editor):
    SymptomType = apps.get_model("participants", "SymptomType")
    SymptomType.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("participants", "0019_symptomtype_symptomsubtype_and_more"),
    ]

    operations = [migrations.RunPython(add_symptom_types, remove_symptom_types)]
