# Generated by Django 5.2.5 on 2025-09-08 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0020_add_symptom_types_20250908_0955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='symptomsubtype',
            old_name='symptom_id',
            new_name='symptom_type',
        ),
    ]
