# Generated by Django 5.2.5 on 2025-09-08 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0021_rename_symptom_id_symptomsubtype_symptom_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participantreportedsymptom',
            old_name='appointment_id',
            new_name='appointment',
        ),
        migrations.RenameField(
            model_name='participantreportedsymptom',
            old_name='participant_id',
            new_name='participant',
        ),
        migrations.RenameField(
            model_name='participantreportedsymptom',
            old_name='symptom_sub_type_id',
            new_name='symptom_sub_type',
        ),
        migrations.RenameField(
            model_name='participantreportedsymptom',
            old_name='symptom_type_id',
            new_name='symptom_type',
        ),
    ]
