# Generated by Django 5.2.5 on 2025-09-08 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0022_rename_appointment_id_participantreportedsymptom_appointment_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ParticipantReportedSymptom',
            new_name='Symptom',
        ),
    ]
