# Generated by Django 5.2.5 on 2025-09-09 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0023_rename_participantreportedsymptom_symptom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='symptom',
            name='participant',
        ),
    ]
