# Generated by Django 5.2.5 on 2025-09-15 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0024_remove_symptom_participant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptom',
            name='investigated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='when_started',
            field=models.CharField(blank=True, choices=[('LESS_THAN_THREE_MONTHS', 'Less than 3 months'), ('THREE MONTHS TO A YEAR', '3 months to a year'), ('ONE_TO_THREE_YEARS', '1 to 3 years'), ('OVER_THREE_YEARS', 'Over 3 years'), ('SINCE_A_SPECIFIC_DATE', 'Since a specific date'), ('NOT_SURE', 'Not sure')]),
        ),
    ]
