# Generated by Django 5.2.5 on 2025-09-16 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0025_alter_symptom_investigated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptom',
            name='investigation_details',
            field=models.CharField(blank=True),
        ),
    ]
