# Generated by Django 5.2.6 on 2025-09-18 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0026_symptom_investigation_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptom',
            name='area',
            field=models.CharField(choices=[('RIGHT_BREAST', 'Right breast'), ('LEFT_BREAST', 'Left breast'), ('BOTH_BREASTS', 'Both breasts'), ('OTHER', 'Other')]),
        ),
    ]
