# Generated by Django 5.2.6 on 2025-09-29 08:26

from django.db import migrations


def add_symptom_sub_types(apps, schema_editor):
    SymptomSubType = apps.get_model("participants", "SymptomSubType")

    SymptomSubType.objects.create(
        symptom_type_id="skin-change", id="sores_or_cysts", name="Sores or cysts"
    )
    SymptomSubType.objects.create(
        symptom_type_id="skin-change",
        id="dimples_or_indentation",
        name="Dimples or indentation",
    )
    SymptomSubType.objects.create(symptom_type_id="skin-change", id="rash", name="Rash")
    SymptomSubType.objects.create(
        symptom_type_id="skin-change", id="colour_change", name="Colour change"
    )
    SymptomSubType.objects.create(
        symptom_type_id="skin-change", id="other", name="Otgher"
    )


def remove_symptom_sub_types(apps, schema_editor):
    SymptomSubType = apps.get_model("participants", "SymptomSubType")
    SymptomSubType.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("participants", "0027_alter_symptom_area"),
    ]

    operations = [migrations.RunPython(add_symptom_sub_types, remove_symptom_sub_types)]
