# Generated by Django 5.2.6 on 2025-09-29 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0028_add_skin_change_subtypes'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptom',
            name='symptom_sub_type_details',
            field=models.CharField(blank=True),
        ),
    ]
