# Generated by Django 5.2.6 on 2025-09-29 12:47

from django.db import migrations
from django.db.models import Value
from django.db.models.functions import Lower, Replace, Upper


def rename_ids(apps, schema_editor):
    SymptomType = apps.get_model("participants", "SymptomType")
    SymptomSubType = apps.get_model("participants", "SymptomSubType")
    Symptom = apps.get_model("participants", "Symptom")

    SymptomType.objects.update(id=Upper(Replace("id", Value("-"), Value("_"))))
    SymptomSubType.objects.update(
        id=Upper(Replace("id", Value("-"), Value("_"))),
        symptom_type=Upper(Replace("symptom_type", Value("-"), Value("_"))),
    )
    Symptom.objects.update(
        symptom_type=Upper(Replace("symptom_type", Value("-"), Value("_")))
    )
    Symptom.objects.update(
        symptom_sub_type=Upper(Replace("symptom_sub_type", Value("-"), Value("_")))
    )


def revert_ids(apps, schema_editor):
    SymptomType = apps.get_model("participants", "SymptomType")
    SymptomSubType = apps.get_model("participants", "SymptomSubType")
    Symptom = apps.get_model("participants", "Symptom")

    SymptomType.objects.update(id=Lower(Replace("id", Value("_"), Value("-"))))
    SymptomSubType.objects.update(
        id=Lower(Replace("id", Value("_"), Value("-"))),
        symptom_type=Lower(Replace("symptom_type", Value("_"), Value("-"))),
    )
    Symptom.objects.update(
        symptom_type=Lower(Replace("symptom_type", Value("_"), Value("-")))
    )
    Symptom.objects.update(
        symptom_sub_type=Lower(Replace("symptom_sub_type", Value("_"), Value("-")))
    )


class Migration(migrations.Migration):

    dependencies = [
        ("participants", "0029_symptom_symptom_sub_type_details"),
    ]

    operations = [
        migrations.RunPython(rename_ids, revert_ids),
    ]
