# Generated by Django 5.2.6 on 2025-10-02 09:55

from django.db import migrations


def add_symptom_sub_types(apps, schema_editor):
    Symptom = apps.get_model("participants", "Symptom")
    SymptomSubType = apps.get_model("participants", "SymptomSubType")

    SymptomSubType.objects.create(
        symptom_type_id="NIPPLE_CHANGE",
        id="NIPPLE_CHANGE_BLOODY_DISCHARGE",
        name="Bloody discharge",
    )
    SymptomSubType.objects.create(
        symptom_type_id="NIPPLE_CHANGE",
        id="NIPPLE_CHANGE_OTHER_DISCHARGE",
        name="Other discharge",
    )
    SymptomSubType.objects.create(
        symptom_type_id="NIPPLE_CHANGE", id="NIPPLE_CHANGE_INVERSION", name="Inversion"
    )
    SymptomSubType.objects.create(
        symptom_type_id="NIPPLE_CHANGE",
        id="NIPPLE_CHANGE_RASH_OR_ECZEMA",
        name="Rash or eczema",
    )
    SymptomSubType.objects.create(
        symptom_type_id="NIPPLE_CHANGE",
        id="NIPPLE_CHANGE_SHAPE_CHANGE",
        name="Shape change",
    )
    SymptomSubType.objects.create(
        symptom_type_id="NIPPLE_CHANGE",
        id="NIPPLE_CHANGE_COLOUR_CHANGE",
        name="Colour change",
    )
    SymptomSubType.objects.create(
        symptom_type_id="NIPPLE_CHANGE", id="NIPPLE_CHANGE_OTHER", name="Other"
    )

    Symptom.objects.filter(symptom_sub_type_id="OTHER").update(
        symptom_sub_type_id="SKIN_CHANGE_OTHER"
    )
    SymptomSubType.objects.filter(id="OTHER").update(
        id="SKIN_CHANGE_OTHER", name="Other"
    )


def remove_symptom_sub_types(apps, schema_editor):
    Symptom = apps.get_model("participants", "Symptom")
    SymptomSubType = apps.get_model("participants", "SymptomSubType")
    SymptomSubType.objects.filter(symptom_type_id="NIPPLE_CHANGE").delete()

    Symptom.objects.filter(symptom_sub_type_id="SKIN_CHANGE_OTHER").update(
        symptom_sub_type_id="OTHER"
    )
    SymptomSubType.objects.filter(id="SKIN_CHANGE_OTHER").update(
        id="OTHER", name="Other"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("participants", "0030_change_symptom_type_id_casing"),
    ]

    operations = [migrations.RunPython(add_symptom_sub_types, remove_symptom_sub_types)]
