# Generated by Django 5.2.7 on 2025-10-28 15:48

import django_fsm
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0031_add_nipple_change_subtypes'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='state',
            field=django_fsm.FSMField(choices=[('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('DID_NOT_ATTEND', 'Did not attend'), ('CHECKED_IN', 'Checked in'), ('SCREENED', 'Screened'), ('PARTIALLY_SCREENED', 'Partially screened'), ('ATTENDED_NOT_SCREENED', 'Attended not screened')], default='CONFIRMED', max_length=50, protected=True),
        ),
        migrations.DeleteModel(
            name='AppointmentStatus',
        ),
    ]
