# Generated by Django 5.2.7 on 2025-10-31 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("participants", "0032_appointmentstatus_created_by_and_more"),
    ]

    operations = [
        # Remove any duplicate statuses
        migrations.RunSQL(
            "DELETE FROM participants_appointmentstatus a USING participants_appointmentstatus b WHERE a.appointment_id=b.appointment_id and a.state=b.state and a.created_at > b.created_at"
        ),
        migrations.AlterUniqueTogether(
            name="appointmentstatus",
            unique_together={("appointment", "state")},
        ),
    ]
