# Generated by Django 5.2.7 on 2025-11-06 12:15

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0033_alter_appointmentstatus_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreastCancerHistoryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diagnosis_location', models.CharField(choices=[('RIGHT_BREAST', 'Right breast'), ('LEFT_BREAST', 'Left breast'), ('BOTH_BREASTS', 'Both breasts'), ('DONT_KNOW', "Don't know")])),
                ('diagnosis_year', models.IntegerField(null=True)),
                ('left_breast_procedure', models.CharField(choices=[('LUMPECTOMY', 'Lumpectomy'), ('MASTECTOMY_TISSUE_REMAINING', 'Mastectomy (tissue remaining)'), ('MASTECTOMY_NO_TISSUE_REMAINING', 'Mastectomy (no tissue remaining)'), ('NO_PROCEDURE', 'No procedure')])),
                ('right_breast_procedure', models.CharField(choices=[('LUMPECTOMY', 'Lumpectomy'), ('MASTECTOMY_TISSUE_REMAINING', 'Mastectomy (tissue remaining)'), ('MASTECTOMY_NO_TISSUE_REMAINING', 'Mastectomy (no tissue remaining)'), ('NO_PROCEDURE', 'No procedure')])),
                ('left_breast_other_surgery', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('LYMPH_NODE_SURGERY', 'Lymph node surgery'), ('RECONSTRUCTION', 'Reconstruction'), ('SYMMETRISATION', 'Symmetrisation'), ('NO_SURGERY', 'No surgery')]), default=list, size=None)),
                ('right_breast_other_surgery', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('LYMPH_NODE_SURGERY', 'Lymph node surgery'), ('RECONSTRUCTION', 'Reconstruction'), ('SYMMETRISATION', 'Symmetrisation'), ('NO_SURGERY', 'No surgery')]), default=list, size=None)),
                ('left_breast_treatment', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('BREAST_RADIOTHERAPY', 'Breast radiotherapy'), ('LYMPH_NODE_RADIOTHERAPY', 'Lymph node radiotherapy'), ('NO_RADIOTHERAPY', 'No radiotherapy')]), default=list, size=None)),
                ('right_breast_treatment', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('BREAST_RADIOTHERAPY', 'Breast radiotherapy'), ('LYMPH_NODE_RADIOTHERAPY', 'Lymph node radiotherapy'), ('NO_RADIOTHERAPY', 'No radiotherapy')]), default=list, size=None)),
                ('systemic_treatments', models.CharField(choices=[('CHEMOTHERAPY', 'Chemotherapy'), ('HORMONE_THERAPY', 'Hormone therapy'), ('OTHER', 'Other'), ('NO_SYSTEMIC_TREATMENTS', 'No systemic treatments')])),
                ('systemic_treatments_other_treatment_details', models.CharField(blank=True, default='')),
                ('intervention_location', models.CharField(choices=[('NHS_HOSPITAL', 'At an NHS hospital'), ('PRIVATE_CLINIC_UK', 'At a private clinic in the UK'), ('OUTSIDE_UK', 'Outside the UK'), ('MULTIPLE_LOCATIONS', 'In multiple locations'), ('EXACT_LOCATION_UNKNOWN', 'Exact location unknown')])),
                ('intervention_location_details', models.CharField(blank=True, default='')),
                ('additional_details', models.TextField(blank=True, default='')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='breast_cancer_history_items', to='participants.appointment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
