# Generated by Django 5.2.7 on 2025-11-10 14:09

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0034_breastcancerhistoryitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='MastectomyOrLumpectomyHistoryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('right_breast_procedure', models.CharField(choices=[('LUMPECTOMY', 'Lumpectomy'), ('MASTECTOMY_TISSUE_REMAINING', 'Mastectomy (tissue remaining)'), ('MASTECTOMY_NO_TISSUE_REMAINING', 'Mastectomy (no tissue remaining)'), ('NO_PROCEDURE', 'No procedure')])),
                ('left_breast_procedure', models.CharField(choices=[('LUMPECTOMY', 'Lumpectomy'), ('MASTECTOMY_TISSUE_REMAINING', 'Mastectomy (tissue remaining)'), ('MASTECTOMY_NO_TISSUE_REMAINING', 'Mastectomy (no tissue remaining)'), ('NO_PROCEDURE', 'No procedure')])),
                ('right_breast_other_surgery', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('RECONSTRUCTION', 'Reconstruction'), ('SYMMETRISATION', 'Symmetrisation'), ('NO_SURGERY', 'No surgery')]), default=list, size=None)),
                ('left_breast_other_surgery', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('RECONSTRUCTION', 'Reconstruction'), ('SYMMETRISATION', 'Symmetrisation'), ('NO_SURGERY', 'No surgery')]), default=list, size=None)),
                ('year_of_surgery', models.IntegerField(blank=True, null=True)),
                ('surgery_reason', models.CharField(choices=[('RISK_REDUCTION', 'Risk reduction'), ('GENDER_AFFIRMATION', 'Gender-affirmation (top surgery)'), ('OTHER_REASON', 'Other reason')])),
                ('additional_details', models.TextField(blank=True, default='')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mastectomy_or_lumpectomy_history_items', to='participants.appointment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
