# Generated by Django 5.2.7 on 2025-11-10 11:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0034_breastcancerhistoryitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImplantedMedicalDeviceHistoryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.CharField(choices=[('CARDIAC_DEVICE', 'Cardiac device (such as a pacemaker or ICD)'), ('HICKMAN_LINE', 'Hickman line'), ('OTHER_MEDICAL_DEVICE', 'Other medical device')])),
                ('other_medical_device_details', models.CharField(blank=True, default='')),
                ('procedure_year', models.IntegerField(null=True)),
                ('removal_year', models.IntegerField(null=True)),
                ('additional_details', models.TextField(blank=True, default='')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='implanted_medical_device_history_items', to='participants.appointment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
