# Generated by Django 5.2.7 on 2025-11-12 09:19

import django.contrib.postgres.fields
import manage_breast_screening.nhsuk_forms.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0035_implantedmedicaldevicehistoryitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breastcancerhistoryitem',
            name='diagnosis_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='breastcancerhistoryitem',
            name='left_breast_other_surgery',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('LYMPH_NODE_SURGERY', 'Lymph node surgery'), ('RECONSTRUCTION', 'Reconstruction'), ('SYMMETRISATION', 'Symmetrisation'), ('NO_SURGERY', 'No surgery')]), default=list, size=None, validators=[manage_breast_screening.nhsuk_forms.validators.ExcludesOtherOptionsValidator('NO_SURGERY', 'No surgery')]),
        ),
        migrations.AlterField(
            model_name='breastcancerhistoryitem',
            name='left_breast_treatment',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('BREAST_RADIOTHERAPY', 'Breast radiotherapy'), ('LYMPH_NODE_RADIOTHERAPY', 'Lymph node radiotherapy'), ('NO_RADIOTHERAPY', 'No radiotherapy')]), default=list, size=None, validators=[manage_breast_screening.nhsuk_forms.validators.ExcludesOtherOptionsValidator('NO_RADIOTHERAPY', 'No radiotherapy')]),
        ),
        migrations.AlterField(
            model_name='breastcancerhistoryitem',
            name='right_breast_other_surgery',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('LYMPH_NODE_SURGERY', 'Lymph node surgery'), ('RECONSTRUCTION', 'Reconstruction'), ('SYMMETRISATION', 'Symmetrisation'), ('NO_SURGERY', 'No surgery')]), default=list, size=None, validators=[manage_breast_screening.nhsuk_forms.validators.ExcludesOtherOptionsValidator('NO_SURGERY', 'No surgery')]),
        ),
        migrations.AlterField(
            model_name='breastcancerhistoryitem',
            name='right_breast_treatment',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('BREAST_RADIOTHERAPY', 'Breast radiotherapy'), ('LYMPH_NODE_RADIOTHERAPY', 'Lymph node radiotherapy'), ('NO_RADIOTHERAPY', 'No radiotherapy')]), default=list, size=None, validators=[manage_breast_screening.nhsuk_forms.validators.ExcludesOtherOptionsValidator('NO_RADIOTHERAPY', 'No radiotherapy')]),
        ),
    ]
