# Generated by Django 5.2.7 on 2025-11-11 09:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0036_breastaugmentationhistoryitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherProcedureHistoryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('procedure', models.CharField(choices=[('BREAST_REDUCTION', 'Breast reduction'), ('BREAST_SYMMETRISATION', 'Breast symmetrisation'), ('NIPPLE_CORRECTION', 'Nipple correction'), ('OTHER', 'Other')])),
                ('procedure_details', models.CharField(blank=True, default='')),
                ('procedure_year', models.IntegerField(null=True)),
                ('additional_details', models.TextField(blank=True, default='')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='other_procedure_history_items', to='participants.appointment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
