# Generated by Django 5.2.7 on 2025-11-11 13:56

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0037_otherprocedurehistoryitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='BenignLumpHistoryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('right_breast_procedures', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('NEEDLE_BIOPSY', 'Needle biopsy'), ('LUMP_REMOVED', 'Lump removed'), ('NO_PROCEDURES', 'No procedures')]), default=list, size=None)),
                ('left_breast_procedures', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('NEEDLE_BIOPSY', 'Needle biopsy'), ('LUMP_REMOVED', 'Lump removed'), ('NO_PROCEDURES', 'No procedures')]), default=list, size=None)),
                ('procedure_year', models.IntegerField(null=True)),
                ('procedure_location', models.CharField(choices=[('NHS_HOSPITAL', 'At an NHS hospital'), ('PRIVATE_CLINIC_UK', 'At a private clinic in the UK'), ('OUTSIDE_UK', 'Outside the UK'), ('MULTIPLE_LOCATIONS', 'In multiple locations'), ('EXACT_LOCATION_UNKNOWN', 'Exact location unknown')])),
                ('procedure_location_details', models.CharField(blank=True, default='')),
                ('additional_details', models.TextField(blank=True, default='')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='benign_lump_history_items', to='participants.appointment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
