# Generated by Django 5.2.7 on 2025-11-12 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0036_alter_breastcancerhistoryitem_diagnosis_year_and_more'),
        ('participants', '0037_otherprocedurehistoryitem'),
    ]

    operations = [
    ]
