# Generated by Django 5.2.7 on 2025-11-12 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0035_mastectomyorlumpectomyhistoryitem'),
        ('participants', '0038_benignlumphistoryitem'),
    ]

    operations = [
    ]
