# Generated by Django 5.2.7 on 2025-11-13 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0038_merge_20251112_1027'),
        ('participants', '0039_merge_20251112_1442'),
    ]

    operations = [
    ]
