# Generated by Django 5.2.8 on 2025-11-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0041_cysthistoryitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='implantedmedicaldevicehistoryitem',
            name='device',
            field=models.CharField(choices=[('CARDIAC_DEVICE', 'Cardiac device (such as a pacemaker or ICD)'), ('HICKMAN_LINE', 'Hickman line'), ('OTHER_MEDICAL_DEVICE', 'Other medical device (or does not know)')]),
        ),
    ]
