# Generated by Django 5.2.8 on 2025-11-17 16:08

import django.contrib.postgres.fields
from django.db import migrations, models

import manage_breast_screening.nhsuk_forms.validators


class Migration(migrations.Migration):

    dependencies = [
        ("participants", "0042_alter_implantedmedicaldevicehistoryitem_device"),
    ]

    operations = [
        migrations.AddField(
            model_name="breastcancerhistoryitem",
            name="systemic_treatments2",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("CHEMOTHERAPY", "Chemotherapy"),
                        ("HORMONE_THERAPY", "Hormone therapy"),
                        ("OTHER", "Other"),
                        ("NO_SYSTEMIC_TREATMENTS", "No systemic treatments"),
                    ]
                ),
                default=list,
                size=None,
                validators=[
                    manage_breast_screening.nhsuk_forms.validators.ExcludesOtherOptionsValidator(
                        "NO_SYSTEMIC_TREATMENTS", "No systemic treatments"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="breastcancerhistoryitem",
            name="systemic_treatments",
            field=models.CharField(
                choices=[
                    ("CHEMOTHERAPY", "Chemotherapy"),
                    ("HORMONE_THERAPY", "Hormone therapy"),
                    ("OTHER", "Other"),
                    ("NO_SYSTEMIC_TREATMENTS", "No systemic treatments"),
                ],
                db_default="NO_SYSTEMIC_TREATMENTS",  # add a default so the migration is reversable
            ),
        ),
        migrations.RunSQL(
            sql="update participants_breastcancerhistoryitem set systemic_treatments2 = ARRAY[systemic_treatments]",
            reverse_sql="update participants_breastcancerhistoryitem set systemic_treatments = systemic_treatments2[1]",
        ),
        migrations.RemoveField(
            model_name="breastcancerhistoryitem", name="systemic_treatments"
        ),
        migrations.RenameField(
            model_name="breastcancerhistoryitem",
            old_name="systemic_treatments2",
            new_name="systemic_treatments",
        ),
    ]
