# Generated by Django 5.2.8 on 2025-11-19 18:01

import django.contrib.postgres.fields
import manage_breast_screening.nhsuk_forms.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0043_alter_breastcancerhistoryitem_systemic_treatments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breastaugmentationhistoryitem',
            name='implants_have_been_removed',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='breastaugmentationhistoryitem',
            name='left_breast_procedures',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('BREAST_IMPLANTS', 'Breast implants (silicone or saline)'), ('OTHER_AUGMENTATION', 'Other augmentation'), ('NO_PROCEDURES', 'No procedures')]), default=list, size=None, validators=[manage_breast_screening.nhsuk_forms.validators.ExcludesOtherOptionsValidator('NO_PROCEDURES', 'No procedures')]),
        ),
        migrations.AlterField(
            model_name='breastaugmentationhistoryitem',
            name='procedure_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='breastaugmentationhistoryitem',
            name='removal_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='breastaugmentationhistoryitem',
            name='right_breast_procedures',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('BREAST_IMPLANTS', 'Breast implants (silicone or saline)'), ('OTHER_AUGMENTATION', 'Other augmentation'), ('NO_PROCEDURES', 'No procedures')]), default=list, size=None, validators=[manage_breast_screening.nhsuk_forms.validators.ExcludesOtherOptionsValidator('NO_PROCEDURES', 'No procedures')]),
        ),
    ]
