# Generated by Django 5.2.8 on 2025-11-20 11:01

import django.contrib.postgres.fields
import manage_breast_screening.nhsuk_forms.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('participants', '0044_alter_breastaugmentationhistoryitem_implants_have_been_removed_and_more')]

    operations = [
        migrations.AlterField(
            model_name='breastcancerhistoryitem',
            name='left_breast_other_surgery',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('LYMPH_NODE_SURGERY', 'Lymph node surgery'), ('RECONSTRUCTION', 'Reconstruction'), ('SYMMETRISATION', 'Symmetrisation'), ('NO_SURGERY', 'No other surgery')]), default=list, size=None, validators=[manage_breast_screening.nhsuk_forms.validators.ExcludesOtherOptionsValidator('NO_SURGERY', 'No other surgery')]),
        ),
        migrations.AlterField(
            model_name='breastcancerhistoryitem',
            name='right_breast_other_surgery',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('LYMPH_NODE_SURGERY', 'Lymph node surgery'), ('RECONSTRUCTION', 'Reconstruction'), ('SYMMETRISATION', 'Symmetrisation'), ('NO_SURGERY', 'No other surgery')]), default=list, size=None, validators=[manage_breast_screening.nhsuk_forms.validators.ExcludesOtherOptionsValidator('NO_SURGERY', 'No other surgery')]),
        ),
    ]
