# Generated by Django 5.2.8 on 2025-11-24 14:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0045_alter_breastcancerhistoryitem_left_breast_other_surgery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastectomyorlumpectomyhistoryitem',
            name='surgery_other_reason_details',
            field=models.CharField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='mastectomyorlumpectomyhistoryitem',
            name='left_breast_other_surgery',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('RECONSTRUCTION', 'Reconstruction'), ('SYMMETRISATION', 'Symmetrisation'), ('NO_OTHER_SURGERY', 'No other surgery')]), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='mastectomyorlumpectomyhistoryitem',
            name='right_breast_other_surgery',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('RECONSTRUCTION', 'Reconstruction'), ('SYMMETRISATION', 'Symmetrisation'), ('NO_OTHER_SURGERY', 'No other surgery')]), default=list, size=None),
        ),
    ]
