# Generated by Django 5.2.8 on 2025-11-25 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0046_mastectomyorlumpectomyhistoryitem_surgery_other_reason_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='implantedmedicaldevicehistoryitem',
            name='device_has_been_removed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
