# Generated by Django 5.2.8 on 2025-11-27 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0047_implantedmedicaldevicehistoryitem_device_has_been_removed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptom',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='symptoms', to='participants.appointment'),
        ),
    ]
