# Generated by Django 5.2.8 on 2025-12-16 11:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0049_appointmentnote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalInformationReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.CharField(choices=[('MAMMOGRAM_HISTORY', 'Mammogram history'), ('SYMPTOMS', 'Symptoms'), ('MEDICAL_HISTORY', 'Medical history'), ('BREAST_FEATURES', 'Breast features'), ('OTHER_INFORMATION', 'Other information')], max_length=50)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medical_information_reviews', to='participants.appointment')),
                ('reviewed_by', models.ForeignKey(help_text='The user who marked this section as reviewed', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['appointment', 'section'], name='participant_appoint_1c0272_idx')],
                'unique_together': {('appointment', 'section')},
            },
        ),
    ]
