# Generated by Django 5.2.8 on 2025-12-30 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0050_medicalinformationreview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointmentstatus',
            old_name='state',
            new_name='name',
        ),
        migrations.AlterUniqueTogether(
            name='appointmentstatus',
            unique_together={('appointment', 'name')},
        ),
    ]
