# Generated by Django 5.2.8 on 2025-12-31 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0051_rename_state_appointmentstatus_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentstatus',
            name='name',
            field=models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('CHECKED_IN', 'Checked in'), ('STARTED', 'Started'), ('IDENTITY_CONFIRMED', 'Identity confirmed'), ('MEDICAL_INFORMATION_REVIEWED', 'Medical information reviewed'), ('IMAGES_TAKEN', 'Images taken'), ('CANCELLED', 'Cancelled'), ('DID_NOT_ATTEND', 'Did not attend'), ('SCREENED', 'Screened'), ('PARTIALLY_SCREENED', 'Partially screened'), ('ATTENDED_NOT_SCREENED', 'Attended not screened')], default='CONFIRMED', max_length=50),
        ),
    ]
