# Generated by Django 5.2.8 on 2026-01-08 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0052_alter_appointmentstatus_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantreportedmammogram',
            name='reason_for_continuing',
            field=models.TextField(blank=True, default=''),
        ),
    ]
