# Generated by Django 5.2.8 on 2026-01-09 17:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0018_userassignment_roles'),
        ('participants', '0053_participantreportedmammogram_reason_for_continuing'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentReportedMammogram',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location_type', models.CharField(choices=[('NHS_BREAST_SCREENING_UNIT', 'At an NHS breast screening unit'), ('ELSEWHERE_UK', 'Elsewhere in the UK'), ('OUTSIDE_UK', 'Outside the UK'), ('PREFER_NOT_TO_SAY', 'Prefer not to say')])),
                ('location_details', models.TextField(blank=True, default='')),
                ('exact_date', models.DateField(blank=True, null=True)),
                ('approx_date', models.CharField(blank=True, default='')),
                ('different_name', models.CharField(blank=True, default='')),
                ('additional_information', models.TextField(blank=True, default='')),
                ('reason_for_continuing', models.TextField(blank=True, default='')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reported_mammograms', to='participants.appointment')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinics.provider')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='ParticipantReportedMammogram',
        ),
    ]
