# Generated by Django 5.2.8 on 2026-01-12 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0053_participantreportedmammogram_reason_for_continuing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participantreportedmammogram',
            name='participant',
        ),
        migrations.AddField(
            model_name='participantreportedmammogram',
            name='appointment',
            field=models.ForeignKey(default='e0a973c8-8630-4cf2-9313-333da3f3c590', on_delete=django.db.models.deletion.PROTECT, related_name='reported_mammograms', to='participants.appointment'),
            preserve_default=False,
        ),
    ]
