# Generated by Django 5.2.8 on 2026-01-19 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0054_remove_participantreportedmammogram_participant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentstatus',
            name='name',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('CHECKED_IN', 'Checked in'), ('STARTED', 'Started'), ('IDENTITY_CONFIRMED', 'Identity confirmed'), ('MEDICAL_INFORMATION_REVIEWED', 'Medical information reviewed'), ('IMAGES_TAKEN', 'Images taken'), ('CANCELLED', 'Cancelled'), ('DID_NOT_ATTEND', 'Did not attend'), ('SCREENED', 'Screened'), ('PARTIALLY_SCREENED', 'Partially screened'), ('ATTENDED_NOT_SCREENED', 'Attended not screened')], default='SCHEDULED', max_length=50),
        ),
    ]
