# Generated by Django 5.2.8 on 2026-01-20 15:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('participants', '0055_rename_confirmed_to_scheduled'), migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.AlterField(
            model_name='appointmentstatus',
            name='name',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('CHECKED_IN', 'Checked in'), ('IN_PROGRESS', 'In progress'), ('CANCELLED', 'Cancelled'), ('DID_NOT_ATTEND', 'Did not attend'), ('SCREENED', 'Screened'), ('PARTIALLY_SCREENED', 'Partially screened'), ('ATTENDED_NOT_SCREENED', 'Attended not screened')], default='SCHEDULED', max_length=50),
        ),
        migrations.CreateModel(
            name='AppointmentWorkflowStepCompletion',
            fields=[
                ('step_name', models.CharField(choices=[('CONFIRM_IDENTITY', 'Confirm identity'), ('REVIEW_MEDICAL_INFORMATION', 'Review medical information'), ('TAKE_IMAGES', 'Take images'), ('CHECK_INFORMATION', 'Check information')], max_length=50)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='completed_workflow_steps', to='participants.appointment')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
