# Generated by Django 6.0.1 on 2026-01-22 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0056_alter_appointmentstatus_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointmentstatus',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='appointmentstatus',
            name='name',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('CHECKED_IN', 'Checked in'), ('IN_PROGRESS', 'In progress'), ('CANCELLED', 'Cancelled'), ('DID_NOT_ATTEND', 'Did not attend'), ('SCREENED', 'Screened'), ('PARTIALLY_SCREENED', 'Partially screened'), ('ATTENDED_NOT_SCREENED', 'Attended not screened'), ('PAUSED', 'Paused')], default='SCHEDULED', max_length=50),
        ),
    ]
