# Generated by Django 6.0.2 on 2026-02-12 11:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0057_alter_appointmentstatus_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreastFeatureAnnotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('annotations_json', models.JSONField(default=list)),
                ('diagram_version', models.IntegerField(default=1)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='breast_features', to='participants.appointment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
