# Generated by Django 6.0.2 on 2026-02-17 13:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0058_breastfeatureannotation'),
    ]

    operations = [
        migrations.CreateModel(
            name='HormoneReplacementTherapy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('YES', 'Yes'), ('NO_BUT_STOPPED_RECENTLY', 'No, but stopped recently'), ('NO', 'No')])),
                ('approx_start_date', models.CharField(blank=True, default='')),
                ('approx_end_date', models.CharField(blank=True, default='')),
                ('approx_previous_duration', models.CharField(blank=True, default='')),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='hormone_replacement_therapy', to='participants.appointment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
