# Generated by Django 6.0.2 on 2026-02-18 12:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0059_hormonereplacementtherapy'),
    ]

    operations = [
        migrations.CreateModel(
            name='PregnancyAndBreastfeeding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pregnancy_status', models.CharField(choices=[('YES', 'Yes'), ('NO_BUT_HAS_BEEN_RECENTLY', 'No, but has been recently'), ('NO', 'No')])),
                ('approx_pregnancy_due_date', models.CharField(blank=True, default='')),
                ('approx_pregnancy_end_date', models.CharField(blank=True, default='')),
                ('breastfeeding_status', models.CharField(choices=[('YES', 'Yes'), ('NO_BUT_STOPPED_RECENTLY', 'No, but stopped recently'), ('NO', 'No')])),
                ('approx_breastfeeding_start_date', models.CharField(blank=True, default='')),
                ('approx_breastfeeding_end_date', models.CharField(choices=[('YES', 'Yes'), ('NO_BUT_STOPPED_RECENTLY', 'No, but stopped recently'), ('NO', 'No')])),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='pregnancy_and_breastfeeding', to='participants.appointment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
