# Generated by Django 6.0.2 on 2026-02-24 14:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0060_pregnancyandbreastfeeding'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherMedicalInformation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('details', models.TextField(blank=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='other_medical_information', to='participants.appointment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
