# Generated by Django 6.0.2 on 2026-03-05 15:55

from django.db import migrations

def add_breast_pain(apps, schema_editor):
    symptom_type = apps.get_model('participants', 'SymptomType')
    symptom_type.objects.get_or_create(id='BREAST_PAIN', defaults={'name': 'Breast pain'})

class Migration(migrations.Migration):
    dependencies = [
        ('participants', '0061_othermedicalinformation'),
    ]

    operations = [
        migrations.RunPython(add_breast_pain),
    ]
