# Generated by Django 6.0.3 on 2026-03-10 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0062_breast_pain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='first_name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='participant',
            name='gender',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='participant',
            name='last_name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='participant',
            name='nhs_number',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='participant',
            name='phone',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='participant',
            name='risk_level',
            field=models.CharField(),
        ),
    ]
