# Generated by Django 6.0.3 on 2026-03-12 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0063_alter_participant_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='nhs_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
