# Generated by Django 6.0.3 on 2026-03-11 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('participants', '0064_alter_participant_nhs_number')]

    operations = [
        migrations.AddField(
            model_name='participantreportedmammogram',
            name='date_type',
            field=models.CharField(choices=[('EXACT', 'Enter an exact date'), ('MORE_THAN_SIX_MONTHS', 'Not sure (at least 6 months ago)'), ('LESS_THAN_SIX_MONTHS', 'Not sure (less than 6 months ago)')], default='MORE_THAN_SIX_MONTHS'),
            preserve_default=False,
        ),
    ]
