# Generated by Django 6.0.3 on 2026-03-17 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("participants", "0065_participantreportedmammogram_date_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="participantreportedmammogram",
            name="provider",
        ),
        migrations.RunSQL(
            sql="update participants_participantreportedmammogram set location_type='SAME_PROVIDER' where location_type='NHS_BREAST_SCREENING_UNIT'",
            reverse_sql="update participants_participantreportedmammogram set location_type='NHS_BREAST_SCREENING_UNIT' where location_type='SAME_PROVIDER'",
        ),
        migrations.AlterField(
            model_name="participantreportedmammogram",
            name="location_type",
            field=models.CharField(
                choices=[
                    ("SAME_PROVIDER", "At this NHS breast screening unit"),
                    ("ANOTHER_NHS_PROVIDER", "At another NHS breast screening unit"),
                    ("ELSEWHERE_UK", "Elsewhere in the UK"),
                    ("OUTSIDE_UK", "Outside the UK"),
                    ("PREFER_NOT_TO_SAY", "Prefer not to say"),
                ]
            ),
        ),
    ]
