# Generated by Django 6.0.3 on 2026-03-17 11:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0021_alter_clinicstatus_options'),
        ('participants', '0065_participantreportedmammogram_date_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmedPreviousMammogram',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location_details', models.TextField(blank=True, default='')),
                ('exact_date', models.DateField(blank=True, null=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_mammograms', to='participants.appointment')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinics.provider')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
