# Generated by Django 6.0.3 on 2026-03-25 12:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0066_remove_participantreportedmammogram_provider_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='participantreportedmammogram',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ConfirmedPreviousMammogram',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location_details', models.TextField(blank=True, default='')),
                ('exact_date', models.DateField()),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_previous_mammograms', to='participants.participant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
