# Generated by Django 6.0.3 on 2026-03-25 12:19
# Updated to use audit log for setting created_by so can make not nullable

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def populate_created_by(apps, schema_editor):
    participant_reported_mammogram = apps.get_model('participants', 'ParticipantReportedMammogram')
    audit_log = apps.get_model('core', 'AuditLog')
    content_type = apps.get_model('contenttypes', 'ContentType')
    user = apps.get_model('users', 'User')

    ct = content_type.objects.get_for_model(participant_reported_mammogram)
    for mammogram in participant_reported_mammogram.objects.filter(created_by=None):
        entry = (
            audit_log.objects.filter(
                content_type=ct,
                object_id=str(mammogram.pk),
                operation='create'
            )
            .order_by('created_at')
            .first()
        )

        if entry and entry.actor:
            user_id = entry.actor_id
        else:
            user_id = user.objects.get(nhs_uid='chloë_robinson').id
            print(f"No audit log entry found for ParticipantReportedMammogram {mammogram.pk}, so using default user {user_id}")

        mammogram.created_by = user.objects.get(pk=user_id)
        mammogram.save(update_fields=['created_by'])
        print(f"Updated ParticipantReportedMammogram {mammogram.pk} with created_by {user_id}")


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0066_remove_participantreportedmammogram_provider_and_more'),
        ('contenttypes', '__latest__'),
        ('core', '__latest__'),
        ('users', '__latest__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Step 1: add nullable column
        migrations.AddField(
            model_name='participantreportedmammogram',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        # Step 2: populate from audit log
        migrations.RunPython(populate_created_by, migrations.RunPython.noop),
        # Step 3: make non-nullable
        migrations.AlterField(
            model_name='participantreportedmammogram',
            name='created_by',
            field=models.ForeignKey(null=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ConfirmedPreviousMammogram',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location_details', models.TextField(blank=True, default='')),
                ('exact_date', models.DateField()),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_previous_mammograms', to='participants.participant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
