# Generated by Django 6.0.4 on 2026-04-10 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0068_appointment_status_appointment_status_changed_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppointmentStatus',
        ),
    ]
