# Generated by Django 6.0.3 on 2026-04-09 12:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bss_batch_id', models.CharField(max_length=255, unique=True)),
                ('bso_batch_id', models.CharField(max_length=255)),
                ('batch_payload_json', models.JSONField()),
            ],
            options={
                'verbose_name_plural': 'Unprocessed batches',
            },
        ),
    ]
