name: 'Test stage'

on:
  workflow_call:
    inputs:
      build_datetime:
        description: 'Build datetime, set by the CI/CD pipeline workflow'
        required: true
        type: string
      build_timestamp:
        description: 'Build timestamp, set by the CI/CD pipeline workflow'
        required: true
        type: string
      build_epoch:
        description: 'Build epoch, set by the CI/CD pipeline workflow'
        required: true
        type: string
      nodejs_version:
        description: 'Node.js version, set by the CI/CD pipeline workflow'
        required: true
        type: string
      python_version:
        description: 'Python version, set by the CI/CD pipeline workflow'
        required: true
        type: string
      terraform_version:
        description: 'Terraform version, set by the CI/CD pipeline workflow'
        required: true
        type: string
      version:
        description: 'Version of the software, set by the CI/CD pipeline workflow'
        required: true
        type: string

jobs:
  test:
    name: 'Tests'
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      notifications-changed: ${{ steps.notifications-changes.outputs.notifications == 'true' }}
      playwright-version: ${{ steps.get-playwright-version.outputs.playwright-version }}
    services:
      postgres:
        image: postgres:17.4-alpine3.21
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v5

      - name: Detect notifications code changes
        uses: dorny/paths-filter@v3
        id: notifications-changes
        with:
          filters: |
            notifications:
              - 'manage_breast_screening/notifications/**'

      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065
        with:
          python-version: '${{inputs.python_version}}'
          cache: poetry
          cache-dependency-path: ./poetry.lock

      - name: Install dependencies
        run: make dependencies

      - name: Get installed Playwright version
        id: get-playwright-version
        run: |
          echo "playwright-version=$(poetry show playwright | awk '/version/ { print $3 }')"
          echo "playwright-version=$(poetry show playwright | awk '/version/ { print $3 }')" >> "$GITHUB_OUTPUT"

      - name: 'Run unit test suite'
        run: make test-unit
        env:
          DATABASE_NAME: postgres
          DATABASE_PASSWORD: postgres
          DATABASE_USER: postgres
          DATABASE_HOST: localhost

  notifications-integration-test:
    needs: test
    if: needs.test.outputs.notifications-changed
    name: 'Notifications Integration Tests'
    runs-on: ubuntu-latest
    timeout-minutes: 5

    services:
      postgres:
        image: postgres:17.4-alpine3.21
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v5

      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065
        with:
          python-version: '${{inputs.python_version}}'
          cache: poetry
          cache-dependency-path: ./poetry.lock

      - name: Install dependencies
        run: make dependencies

  test-lint:
    name: 'Linting'
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v5

      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065
        with:
          python-version: '${{inputs.python_version}}'
          cache: poetry
          cache-dependency-path: ./poetry.lock

      - name: Install dependencies
        run: make dependencies

      - name: Run linting
        run: make test-lint

  perform-static-analysis:
    name: 'Perform static analysis'
    needs: [test]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    timeout-minutes: 5
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v5
        with:
          fetch-depth: 0 # Full history is needed to improving relevancy of reporting
      - name: 'Perform static analysis'
        uses: ./.github/actions/perform-static-analysis
        with:
          sonar_organisation_key: '${{ vars.SONAR_ORGANISATION_KEY }}'
          sonar_project_key: '${{ vars.SONAR_PROJECT_KEY }}'
          sonar_token: '${{ secrets.SONAR_TOKEN }}'

  playwright-integration-test:
    # TODO: add path-filter
    needs: test
    name: 'Tests (playwright)'
    runs-on: ubuntu-latest

    # Use the containerised version of playwright, to avoid the additional step
    # of downloading and installing browsers, which is slow.
    container:
      image: 'mcr.microsoft.com/playwright/python:v${{needs.test.outputs.playwright-version}}-noble'
      options: --user 1001
    timeout-minutes: 5

    services:
      postgres:
        image: postgres:17.4-alpine3.21
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v4

      - name: Install poetry
        # poetry must be installed first to use setup-python's
        # caching.
        # pipx is not available in this image, so just use pip.
        # this defaults to a user installation, so make sure the path
        # is properly set up for this.
        run: |
          echo "/github/home/.local/bin" >> $GITHUB_PATH
          pip install poetry

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065
        with:
          python-version: '${{inputs.python_version}}'
          cache: poetry
          cache-dependency-path: ./poetry.lock

      - name: Install python and node dependencies
        # Make is not available in this image, so just use poetry/npm directly
        run: |
          poetry install
          npm ci

      - name: 'Run system test suite'
        run: make test-ui
        env:
          DATABASE_NAME: postgres
          DATABASE_PASSWORD: postgres
          DATABASE_USER: postgres
          DATABASE_HOST: localhost
