name: 'Test stage'

on:
  workflow_call:
    inputs:
      build_datetime:
        description: 'Build datetime, set by the CI/CD pipeline workflow'
        required: true
        type: string
      build_timestamp:
        description: 'Build timestamp, set by the CI/CD pipeline workflow'
        required: true
        type: string
      build_epoch:
        description: 'Build epoch, set by the CI/CD pipeline workflow'
        required: true
        type: string
      nodejs_version:
        description: 'Node.js version, set by the CI/CD pipeline workflow'
        required: true
        type: string
      python_version:
        description: 'Python version, set by the CI/CD pipeline workflow'
        required: true
        type: string
      terraform_version:
        description: 'Terraform version, set by the CI/CD pipeline workflow'
        required: true
        type: string
      version:
        description: 'Version of the software, set by the CI/CD pipeline workflow'
        required: true
        type: string

jobs:
  test_playwright:
    name: 'Tests (playwright)'
    runs-on: 'mcr.microsoft.com/playwright/python:v1.52.0-noble'
    timeout-minutes: 5

    services:
      postgres:
        image: postgres:17.4-alpine3.21
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v4

      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065
        with:
          python-version: '${{inputs.python_version}}'
          cache: poetry
          cache-dependency-path: ./poetry.lock

      - name: Install dependencies
        run: make dependencies

      - name: Get installed Playwright version
        id: playwright-version
        run: echo -n "::set-output name=version::$(poetry show playwright | awk '/version/ { print $3 }')"

      - name: Cache playwright browsers
        id: playwright-cache
        uses: actions/cache@v4.2.3
        with:
          # Use faster GNU tar for all runners
          enableCrossOsArchive: true
          path: '~/.cache/ms-playwright'
          key: '${{ runner.os }}-playwright-${{ steps.playwright-version.outputs.version }}'
          restore-keys: |
            ${{ runner.os }}-playwright-

      - name: Install Playwright browsers
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: poetry run playwright install chromium --only-shell

      - name: 'Run system test suite'
        run: make test-ui
        env:
          DATABASE_NAME: postgres
          DATABASE_PASSWORD: postgres
          DATABASE_USER: postgres
          DATABASE_HOST: localhost

  test:
    name: 'Tests'
    runs-on: ubuntu-latest
    timeout-minutes: 5

    services:
      postgres:
        image: postgres:17.4-alpine3.21
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v4

      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065
        with:
          python-version: '${{inputs.python_version}}'
          cache: poetry
          cache-dependency-path: ./poetry.lock

      - name: Install dependencies
        run: make dependencies

      - name: Get installed Playwright version
        id: playwright-version
        run: echo -n "::set-output name=version::$(poetry show playwright | awk '/version/ { print $3 }')"

      - name: Install Playwright dependencies
        run: poetry run playwright install-deps

      - name: Cache playwright browsers
        id: playwright-cache
        uses: actions/cache@v4.2.3
        with:
          # Use faster GNU tar for all runners
          enableCrossOsArchive: true
          path: '~/.cache/ms-playwright'
          key: '${{ runner.os }}-playwright-${{ steps.playwright-version.outputs.version }}'
          restore-keys: |
            ${{ runner.os }}-playwright-

      - name: Install Playwright browsers
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: poetry run playwright install chromium --only-shell

      - name: 'Run unit test suite'
        run: make test-unit
        env:
          DATABASE_NAME: postgres
          DATABASE_PASSWORD: postgres
          DATABASE_USER: postgres
          DATABASE_HOST: localhost

  test-lint:
    name: 'Linting'
    runs-on: ubuntu-latest
    timeout-minutes: 1

    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v4

      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065
        with:
          python-version: '${{inputs.python_version}}'
          cache: poetry
          cache-dependency-path: ./poetry.lock

      - name: Install dependencies
        run: make dependencies

      - name: Run linting
        run: make test-lint

  perform-static-analysis:
    name: 'Perform static analysis'
    needs: [test]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    timeout-minutes: 5
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Full history is needed to improving relevancy of reporting
      - name: 'Perform static analysis'
        uses: ./.github/actions/perform-static-analysis
        with:
          sonar_organisation_key: '${{ vars.SONAR_ORGANISATION_KEY }}'
          sonar_project_key: '${{ vars.SONAR_PROJECT_KEY }}'
          sonar_token: '${{ secrets.SONAR_TOKEN }}'
