name: Deploy stage

on:
  workflow_call:
    inputs:
      env:
        description: "which environment to deploy to"
        required: true
        type: string

jobs:
  deploy:
    name: "Deploy to an environment"
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - run: |
          echo "Deploying to environment ${{inputs.env}}"