name: Update Schema Diagram

on:
  workflow_call:
    inputs:
      python_version:
        required: true
        type: string

jobs:
  update-schema:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ github.token }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python_version }}

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y graphviz graphviz-dev

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          # Install pygraphviz with explicit include and library paths
          CFLAGS="-I/usr/include/graphviz" LDFLAGS="-L/usr/lib/graphviz" poetry run pip install --no-cache-dir pygraphviz
          poetry install

      - name: Generate schema diagram
        run: |
          poetry run python scripts/generate_schema_diagram.py

      - name: Check for changes
        id: git-check
        run: |
          git add docs/diagrams/database-schema.png docs/diagrams/database-schema.puml
          git diff --staged --quiet || echo "changes=true" >> $GITHUB_OUTPUT

      - name: Commit changes
        if: steps.git-check.outputs.changes == 'true'
        uses: EndBug/add-and-commit@v9
        with:
          add: 'docs/diagrams/database-schema.png docs/diagrams/database-schema.puml'
          message: 'Update database schema diagrams [skip ci]'
          push: 'origin HEAD:${{ github.head_ref }}'
          default_author: github_actions
